import type { CircuitDocument, CircuitExample } from './circuit.ts'

function baseDocument(title: string): CircuitDocument {
  return {
    schemaVersion: 1, boardVersion: 'virtual-1', title,
    parts: [], wires: [], probes: { CH1: null, CH2: null },
    instruments: { frequency: 220, amplitude: 2.5, waveform: 'sine', cv: 2 },
  }
}

const activeHardware = 'Connect TL072 DIP-8 pin 8 to +12 V and pin 4 to −12 V. Keep the two 100 nF bypass capacitors C3/C4 close to the IC, one from each supply to GND.'

export const activeExamples: CircuitExample[] = [
  {
    id: 'cv-mixer', name: 'Audio + CV mixer', level: 'Intermediate',
    description: 'Add a DC offset to an audio signal, a useful building block for mixing synth control voltages.',
    whatToChange: 'Change CV from +2 V to −2 V. Return CV to +2 V, then change R2 from 100 kΩ to 47 kΩ.',
    whatToObserve: 'CH2 follows CH1 with a +2 V offset; negative CV moves it down by 4 V. With R2 at 47 kΩ, the positive offset grows to about 4.26 V while the audio amplitude stays near 2.5 V peak.',
    why: 'U1A sums OSC through R1 and CV through R2 with feedback R3. U1B inverts the sum again, so equal R1/R3 and R4/R5 give approximately OSC + CV. The CV contribution is weighted by R3/R2. The 100 kΩ inputs mix signals without directly connecting source outputs; the virtual oscillator’s 100 Ω resistance slightly reduces its contribution. These stages pass DC as well as audio, unlike an AC-coupled mixer.',
    hardware: `${activeHardware} Use five 100 kΩ resistors; the suggested change uses 47 kΩ. Feed LABOR’s DC source into the CV input and measure the offset voltage.`,
    document: {
      ...baseDocument('Audio + CV mixer'),
      parts: [
        { id: 'U1', kind: 'opamp', value: 1, pins: ['e13', 'e14', 'e15', 'e16', 'f16', 'f15', 'f14', 'f13'] },
        { id: 'R1', kind: 'resistor', value: 100_000, pins: ['a6', 'a11'] },
        { id: 'R2', kind: 'resistor', value: 100_000, pins: ['c8', 'c14'] },
        { id: 'R3', kind: 'resistor', value: 100_000, pins: ['a13', 'a18'] },
        { id: 'R4', kind: 'resistor', value: 100_000, pins: ['g20', 'g26'] },
        { id: 'R5', kind: 'resistor', value: 100_000, pins: ['j23', 'j26'] },
        { id: 'C3', kind: 'capacitor', value: 100e-9, pins: ['h9', 'h13'] },
        { id: 'C4', kind: 'capacitor', value: 100e-9, pins: ['c16', 'c20'] },
      ],
      wires: [
        { id: 'W1', from: 'osc', to: 'b6', color: '#56c7c2' },
        { id: 'W2', from: 'cv', to: 'b8', color: '#b899ce' },
        { id: 'W3', from: 'b11', to: 'b14', color: '#56c7c2' },
        { id: 'W4', from: 'b13', to: 'j20', color: '#c8a55b' },
        { id: 'W5', from: 'vplus', to: 'j13', color: '#d98870' },
        { id: 'W6', from: 'vminus', to: 'a16', color: '#798bbf' },
        { id: 'W7', from: 'gnd', to: 'tn10', color: '#6a839b' },
        { id: 'W8', from: 'j9', to: 'tn11', color: '#6a839b' },
        { id: 'W9', from: 'd20', to: 'tn12', color: '#6a839b' },
        { id: 'W10', from: 'a15', to: 'tn13', color: '#6a839b' },
        { id: 'W11', from: 'j16', to: 'tn14', color: '#6a839b' },
        { id: 'W12', from: 'b18', to: 'd14', color: '#c8a55b' },
        { id: 'W13', from: 'i26', to: 'j15', color: '#c8a55b' },
        { id: 'W14', from: 'i23', to: 'j14', color: '#c8a55b' },
      ],
      probes: { CH1: 'c6', CH2: 'j14' },
    },
  },
  {
    id: 'attenuverter', name: 'Buffered attenuverter', level: 'Intermediate',
    description: 'Turn modulation depth through zero into an inverted signal with a single knob.',
    whatToChange: 'Move linear potentiometer P1 from 75% to 50%, then to 0% and 100%.',
    whatToObserve: 'CH2 starts at half the input amplitude. The center position nearly cancels the signal; 0% gives an inverted copy and 100% gives a positive copy. CH1 stays near 2.5 V peak.',
    why: 'U1A buffers the input so the potentiometer and resistor network do not load the source significantly. P1 feeds a fraction p of that buffered signal to U1B’s positive input. Equal R1 and R2 make its output approximately (2p − 1) × input: −1 at CCW, 0 at center, +1 at CW. It can scale bipolar audio or a slowly changing control voltage; a real pot and resistor tolerances determine the exact null.',
    hardware: `${activeHardware} Add a 10 kΩ linear pot and two 100 kΩ resistors. Wire the pot lugs as CCW, wiper and CW, using leads if its footprint differs.`,
    document: {
      ...baseDocument('Buffered attenuverter'),
      parts: [
        { id: 'U1', kind: 'opamp', value: 1, pins: ['e13', 'e14', 'e15', 'e16', 'f16', 'f15', 'f14', 'f13'] },
        { id: 'P1', kind: 'potentiometer', value: 10_000, position: 0.75, pins: ['a5', 'a6', 'a7'] },
        { id: 'R1', kind: 'resistor', value: 100_000, pins: ['g20', 'g26'] },
        { id: 'R2', kind: 'resistor', value: 100_000, pins: ['j23', 'j26'] },
        { id: 'C3', kind: 'capacitor', value: 100e-9, pins: ['h9', 'h13'] },
        { id: 'C4', kind: 'capacitor', value: 100e-9, pins: ['c16', 'c20'] },
      ],
      wires: [
        { id: 'W1', from: 'osc', to: 'a15', color: '#56c7c2' },
        { id: 'W2', from: 'c13', to: 'c14', color: '#c8a55b' },
        { id: 'W3', from: 'a13', to: 'b7', color: '#56c7c2' },
        { id: 'W4', from: 'b13', to: 'j20', color: '#56c7c2' },
        { id: 'W5', from: 'b6', to: 'j16', color: '#b899ce' },
        { id: 'W6', from: 'vplus', to: 'j13', color: '#d98870' },
        { id: 'W7', from: 'vminus', to: 'a16', color: '#798bbf' },
        { id: 'W8', from: 'gnd', to: 'tn10', color: '#6a839b' },
        { id: 'W9', from: 'j9', to: 'tn11', color: '#6a839b' },
        { id: 'W10', from: 'd20', to: 'tn12', color: '#6a839b' },
        { id: 'W11', from: 'b5', to: 'tn13', color: '#6a839b' },
        { id: 'W12', from: 'i26', to: 'j15', color: '#c8a55b' },
        { id: 'W13', from: 'i23', to: 'j14', color: '#c8a55b' },
      ],
      probes: { CH1: 'b15', CH2: 'j14' },
    },
  },
  {
    id: 'sallen-key-filter', name: 'Two-pole synth low-pass', level: 'Advanced',
    description: 'Build a Sallen–Key low-pass and explore how feedback changes the emphasis near its cutoff.',
    whatToChange: 'Change feedback resistor R3 from 4.7 kΩ to 10 kΩ. Compare both settings at 160 Hz, then sweep OSC from 20 Hz to 1 kHz.',
    whatToObserve: 'At 160 Hz, CH2 rises from about 2.4 V peak to about 5 V peak when R3 increases. Higher frequencies fall away at roughly 12 dB per octave well above cutoff. Raising R3 also increases low-frequency gain from about 1.47 to 2.',
    why: 'Equal R1/R2 = 10 kΩ and C1/C2 = 100 nF set the nominal pole frequency near 159 Hz. The amplifier gain K = 1 + R3/R4 makes Q approximately 1/(3 − K): about 0.65 initially and 1 with R3 = 10 kΩ. C1 feeds the output back into the RC network, producing a two-pole response and stronger emphasis at higher Q. This is a fixed-frequency filter, not a voltage-controlled filter; neither suggested setting self-oscillates. U1B is a grounded follower so its unused inputs remain defined.',
    hardware: `${activeHardware} Add three 10 kΩ resistors, one 4.7 kΩ feedback resistor and two further 100 nF capacitors. Component tolerances and source resistance shift the pole frequency and Q slightly.`,
    document: {
      ...baseDocument('Two-pole synth low-pass'),
      instruments: { frequency: 160, amplitude: 2.5, waveform: 'sine', cv: 0 },
      parts: [
        { id: 'U1', kind: 'opamp', value: 1, pins: ['e13', 'e14', 'e15', 'e16', 'f16', 'f15', 'f14', 'f13'] },
        { id: 'R1', kind: 'resistor', value: 10_000, pins: ['a5', 'a9'] },
        { id: 'R2', kind: 'resistor', value: 10_000, pins: ['a18', 'a24'] },
        { id: 'R3', kind: 'resistor', value: 4_700, pins: ['a13', 'a14'] },
        { id: 'R4', kind: 'resistor', value: 10_000, pins: ['g22', 'g28'] },
        { id: 'C1', kind: 'capacitor', value: 100e-9, pins: ['c9', 'c13'] },
        { id: 'C2', kind: 'capacitor', value: 100e-9, pins: ['c24', 'c28'] },
        { id: 'C3', kind: 'capacitor', value: 100e-9, pins: ['h9', 'h13'] },
        { id: 'C4', kind: 'capacitor', value: 100e-9, pins: ['c16', 'c20'] },
      ],
      wires: [
        { id: 'W1', from: 'osc', to: 'b5', color: '#56c7c2' },
        { id: 'W2', from: 'vplus', to: 'j13', color: '#d98870' },
        { id: 'W3', from: 'vminus', to: 'a16', color: '#798bbf' },
        { id: 'W4', from: 'gnd', to: 'tn10', color: '#6a839b' },
        { id: 'W5', from: 'j9', to: 'tn11', color: '#6a839b' },
        { id: 'W6', from: 'd20', to: 'tn12', color: '#6a839b' },
        { id: 'W7', from: 'd28', to: 'tn13', color: '#6a839b' },
        { id: 'W8', from: 'j28', to: 'tn14', color: '#6a839b' },
        { id: 'W9', from: 'j16', to: 'tn15', color: '#6a839b' },
        { id: 'W10', from: 'j14', to: 'j15', color: '#c8a55b' },
        { id: 'W11', from: 'd9', to: 'b18', color: '#56c7c2' },
        { id: 'W12', from: 'b24', to: 'b15', color: '#56c7c2' },
        { id: 'W13', from: 'j22', to: 'd14', color: '#c8a55b' },
      ],
      probes: { CH1: 'c5', CH2: 'b13' },
    },
  },
]
