import type { CircuitDocument, CircuitExample } from './circuit.ts'
import type { CustomComponent } from './custom-components.ts'

const resistor: CustomComponent = { id: 'current_resistor', name: 'Current-sensitive resistor', description: 'Instantaneous symmetric R(|I|); no heating or cooling memory.', modelVersion: 1, baseKind: 'resistor', characteristic: { type: 'resistance-current', axis: 'current-magnitude', interpolation: 'linear', extrapolation: 'constant', points: [{ x: 0, y: 1000 }, { x: 0.001, y: 1200 }, { x: 0.005, y: 2000 }, { x: 0.01, y: 4000 }] } }
const capacitor: CustomComponent = { id: 'voltage_capacitor', name: 'Voltage-sensitive capacitor', description: 'Differential capacitance rises with signed voltage; endpoint values extend beyond ±5 V.', modelVersion: 1, baseKind: 'capacitor', characteristic: { type: 'capacitance-voltage', axis: 'signed-voltage', interpolation: 'linear', extrapolation: 'constant', points: [{ x: -5, y: 50e-9 }, { x: 0, y: 100e-9 }, { x: 5, y: 200e-9 }] } }
const circuit = (model: CustomComponent): CircuitDocument => ({
  schemaVersion: 3, boardVersion: 'virtual-1', title: model.name, customComponents: [model],
  instruments: { frequency: 100, amplitude: 5, waveform: 'sine', cv: 5 },
  parts: [{ id: 'R1', kind: 'resistor', value: 1000, pins: ['a6', 'a12'], ...(model.baseKind === 'resistor' ? { customModelId: model.id } : {}) }, { id: model.baseKind === 'resistor' ? 'R2' : 'C1', kind: model.baseKind === 'resistor' ? 'resistor' : 'capacitor', value: model.baseKind === 'resistor' ? 1000 : 100e-9, pins: ['e12', 'f12'], ...(model.baseKind === 'capacitor' ? { customModelId: model.id } : {}) }],
  wires: [{ id: 'W1', from: 'osc', to: 'b6', color: '#c8a55b' }, { id: 'W2', from: 'gnd', to: 'j12', color: '#91bfad' }], probes: { CH1: 'd6', CH2: 'd12' },
})
export const customExamples: CircuitExample[] = [
  { id: 'custom-resistance', name: resistor.name, level: 'Intermediate', description: 'Explore a symmetric resistance versus current curve.', whatToChange: 'Inspect R1, open Edit model, and compare the four-point curve with a constant 1 kΩ model. Try lower signal amplitudes.', whatToObserve: 'The 1 kΩ load voltage peaks near 2.07 V at a 5 V input, instead of 2.5 V for a linear divider. Recorded current follows the solver; R1’s displayed 1 kΩ is nominal.', why: 'R1 increases with current magnitude and compresses both polarities symmetrically. Linear interpolation applies to R, not V. Beyond 10 mA it stays at 4 kΩ; this model has no thermal memory.', hardware: 'This is an illustrative custom law, not a calibrated physical resistor. A normal 1 kΩ resistor produces a linear divider.', document: circuit(resistor) },
  { id: 'custom-capacitance', name: capacitor.name, level: 'Intermediate', description: 'Explore differential capacitance and stored energy.', whatToChange: 'Inspect C1 and its recording. Increase the oscillator frequency to 1 kHz, then replace its curve with a constant 100 nF model.', whatToObserve: 'Positive and negative swings have different curvature because capacitance ranges from 50 nF at −5 V to 200 nF at +5 V. Recorded capacitance and stored energy follow voltage.', why: 'C is dQ/dV. The solver integrates the curve to charge and the readout integrates V×C(V) to energy. Constant endpoint extension applies outside ±5 V; each capture starts at its DC operating point.', hardware: 'This is an illustrative voltage-dependent law. A normal 100 nF capacitor is approximately linear; a real nonlinear dielectric requires measured data and may have losses absent here.', document: circuit(capacitor) },
]
