import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { examples } from '../../src/lib/circuit'

async function openTab(page: Page, name: 'Circuit' | 'Results' | 'Automations') {
  await page.getByRole('tablist', { name: 'Workspace' }).getByRole('tab', { name, exact: true }).click()
}

test('voltage-triggered example changes the capture and its events seek the recording', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('voltage-triggered-release')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await openTab(page, 'Automations')
  const panel = page.getByRole('region', { name: 'Automations', exact: true })
  await expect(panel).toContainText('2 of 2 fired')
  await expect(panel).toContainText('Fired at 19.')
  await panel.getByRole('button', { name: /Fired at 19\./ }).click()
  await expect(page.getByRole('tablist', { name: 'Workspace' }).getByRole('tab', { name: 'Results', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('Time per division')).toHaveValue('10')
  expect(Number(await page.getByLabel('Recording time milliseconds').inputValue())).toBeGreaterThan(19)
  expect(Number(await page.getByLabel('Recording time milliseconds').inputValue())).toBeLessThan(20)
  await page.getByLabel('Recording time milliseconds').fill('15')
  await openTab(page, 'Circuit')
  await expect(page.getByLabel('Gate automated value', { exact: true })).toHaveText('High')
  await openTab(page, 'Results')
  await page.getByLabel('Recording time milliseconds').fill('30')
  await openTab(page, 'Circuit')
  await expect(page.getByLabel('Gate automated value', { exact: true })).toHaveText('Low')
  await openTab(page, 'Results')
  expect(parseFloat(await page.getByLabel('CH2 recorded voltage', { exact: true }).innerText())).toBeLessThan(1.1)
  await openTab(page, 'Automations')
  await page.screenshot({ path: testInfo.outputPath('automations-recording-desktop.png') })
  await panel.getByRole('button', { name: 'Edit Release at threshold', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Voltage threshold').fill('6')
  await page.getByRole('dialog').getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await expect(panel).toContainText('Threshold not reached')
  await expect(panel).toContainText('1 of 2 fired')
  expect(errors).toEqual([])
})

test('a new ramp is undoable, repeatable and survives export, import and browser recovery', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('voltage-divider')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await openTab(page, 'Automations')
  await page.getByText('Auto update', { exact: true }).click()
  const panel = page.getByRole('region', { name: 'Automations', exact: true })
  await panel.getByRole('button', { name: 'Add automation', exact: true }).click()
  const editor = page.getByRole('dialog')
  await editor.getByLabel('Name', { exact: true }).fill('Fade CV')
  await editor.getByLabel(/^Start time/).fill('10')
  await editor.getByRole('combobox', { name: 'Control', exact: true }).selectOption('cv')
  await editor.getByRole('combobox', { name: 'Change', exact: true }).selectOption('ramp')
  await editor.getByLabel(/^Target value/).fill('2')
  await editor.getByLabel(/^Ramp duration/).fill('20')
  await editor.getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(panel).toContainText('Fade CV')
  await openTab(page, 'Results')
  await expect(page.getByLabel('Recording timeline')).toBeDisabled()
  await page.getByRole('button', { name: 'Simulate', exact: true }).click()
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await page.getByLabel('Recording time milliseconds').fill('20')
  await expect(page.getByLabel('CH2 recorded voltage', { exact: true })).toHaveText('1.750 V')
  await openTab(page, 'Circuit')
  await expect(page.getByLabel('CV automated value', { exact: true })).toHaveText('3.50 V')
  await expect(page.getByRole('spinbutton', { name: 'CV output', exact: true })).toHaveValue('5')
  await openTab(page, 'Automations')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(panel.locator('.automation-row')).toHaveCount(0)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(panel.locator('.automation-row')).toHaveCount(1)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit', exact: true }).click()
  const download = await downloadPromise
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(exported.schemaVersion).toBe(4)
  expect(exported.automations).toBeUndefined()
  expect(exported.automationProgram.definitions[1].name).toBe('Fade CV')
  expect(exported.instruments.cv).toBe(5)
  expect(exported.automationEvents).toBeUndefined()
  await page.getByLabel('Load example').selectOption('rc-filter')
  await page.locator('input[type="file"]').setInputFiles({ name: 'automated-divider.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) })
  await openTab(page, 'Automations')
  await expect(panel).toContainText('Fade CV')
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1') ?? '{}').automationProgram?.definitions?.[1]?.name)).toBe('Fade CV')
  await page.reload()
  await openTab(page, 'Automations')
  await expect(panel).toContainText('Fade CV')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await openTab(page, 'Results')
  await page.getByLabel('Recording time milliseconds').fill('40')
  await expect(page.getByLabel('CH2 recorded voltage', { exact: true })).toHaveText('1.000 V')
})

test('automation editor validates drafts, isolates shortcuts and fits a narrow screen', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('automated-pot-sweep')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await openTab(page, 'Results')
  await page.getByLabel('Recording time milliseconds').fill('30')
  await openTab(page, 'Circuit')
  await expect(page.getByLabel('P1 automated value', { exact: true })).toHaveText('50.0%')
  await openTab(page, 'Automations')
  const panel = page.getByRole('region', { name: 'Automations', exact: true })
  await panel.getByRole('button', { name: 'Duplicate Turn up', exact: true }).click()
  const editor = page.getByRole('dialog')
  await editor.getByLabel('Name', { exact: true }).fill('')
  await editor.getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(editor.getByRole('alert')).toContainText('Give this automation a name')
  await editor.getByLabel('Name', { exact: true }).fill('Sweep copy')
  await editor.getByLabel(/^Wiper position/).fill('101')
  await editor.getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(editor.getByRole('alert')).toContainText('between 0 and 100')
  await editor.getByLabel(/^Wiper position/).fill('80')
  await editor.getByLabel('Name', { exact: true }).press('Control+Enter')
  await expect(editor).toBeVisible()
  await editor.getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(panel.locator('.automation-row')).toHaveCount(3)
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await page.setViewportSize({ width: 390, height: 844 })
  await openTab(page, 'Automations')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('automations-mobile.png') })
  await panel.getByRole('button', { name: 'Edit Sweep copy', exact: true }).click()
  await editor.getByRole('button', { name: 'On voltage crossing', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('automation-editor-mobile.png') })
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(panel).toContainText('At 10 ms')
  await panel.getByRole('button', { name: 'Edit Sweep copy', exact: true }).press('Backspace')
  await openTab(page, 'Circuit')
  await expect(page.locator('[data-part="P1"]')).toHaveCount(1)
  await openTab(page, 'Automations')
  await panel.getByRole('button', { name: 'Delete Sweep copy', exact: true }).click()
  await expect(panel.locator('.automation-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(panel.locator('.automation-row')).toHaveCount(3)
})

test('disabled and unavailable actions explain why they will not run', async ({ page }) => {
  const circuit = structuredClone(examples.find(example => example.id === 'automated-pot-sweep')!.document)
  circuit.automations![0].enabled = false
  circuit.automations![1].trigger = { kind: 'time', atMs: 100 }
  circuit.automations!.push({ id: 'missing', name: 'Missing switch', enabled: true, trigger: { kind: 'time', atMs: 10 }, action: { target: 'switch', partId: 'S99', value: 1, durationMs: 0 } })
  await page.addInitScript(document => localStorage.setItem('labor-playground.document.v1', JSON.stringify(document)), circuit)
  await page.goto('/')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await openTab(page, 'Automations')
  const panel = page.getByRole('region', { name: 'Automations', exact: true })
  await expect(panel).toContainText('Disabled')
  await expect(panel).toContainText(/recording (duration|ends)/i)
  await expect(panel).toContainText(/Missing target|unavailable/i)
  await expect(panel).toContainText('0 of 2 fired')
})
