import { expect, test } from '@playwright/test'

test('Simple dependencies share the Flow model, survive undo and do not solve on layout edits', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('automated-pot-sweep')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await page.getByRole('tab', { name: 'Automations', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Turn down', exact: true }).click()
  const editor = page.getByRole('dialog')
  await editor.getByRole('button', { name: 'After another automation' }).click()
  await editor.getByLabel('After automation finishes').selectOption('Call_A1')
  await editor.getByLabel('Delay (ms)', { exact: true }).fill('10')
  await editor.getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(page.getByText('After Turn up finishes + 10 ms')).toBeVisible()
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await expect(page.getByRole('button', { name: /Fired at 60 ms/ })).toBeVisible()
  await page.getByRole('button', { name: 'Flow', exact: true }).click()
  await expect(page.locator('.flow-canvas .react-flow__node')).toHaveCount(5)
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!).automationProgram)
  await page.getByRole('button', { name: 'Arrange flow', exact: true }).click()
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!).automationProgram)).toEqual(before)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.flow-canvas')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('flow-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('a saved test passes, a circuit mutation fails, and recordings remain separate', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('voltage-divider')
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready')
  await page.getByRole('tab', { name: 'Automations', exact: true }).click()
  await page.getByRole('button', { name: 'Tests (0)', exact: true }).click()
  await page.getByRole('button', { name: 'Add test', exact: true }).click()
  const wizard = page.getByRole('dialog', { name: 'Create circuit test' })
  await wizard.getByLabel('Name', { exact: true }).fill('Divider stays correct')
  await wizard.getByRole('button', { name: 'Save and run', exact: true }).click()
  await expect(wizard).not.toBeVisible()
  const tests = page.getByRole('region', { name: 'Circuit tests' })
  await expect(tests.locator('.test-verdict')).toContainText('passed')
  await tests.getByRole('button', { name: 'Inspect recording', exact: true }).click()
  await expect(page.locator('.test-recording-banner')).toContainText('Divider stays correct')
  await page.getByRole('button', { name: 'Ordinary recording', exact: true }).click()
  await expect(page.locator('.test-recording-banner')).toHaveCount(0)
  // Mutate the current circuit while retaining the saved scenario.
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!))
  saved.parts.find((p: { id: string }) => p.id === 'R2').value = 1000
  await page.locator('input[type="file"]').setInputFiles({ name: 'fault.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(saved)) })
  await page.getByRole('tab', { name: 'Automations', exact: true }).click()
  await expect(tests.locator('.test-verdict')).toContainText('stale')
  await tests.getByRole('button', { name: 'Run all tests', exact: true }).click()
  await expect(tests.locator('.test-verdict')).toContainText('failed')
  await expect(tests).toContainText('observed')
  await page.screenshot({ path: testInfo.outputPath('test-failure-desktop.png'), fullPage: true })
  expect(errors).toEqual([])
})
