import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

const terminal = (page: Page, id: string) => page.locator(`[data-terminal="${id}"]`)
const recovered = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1') ?? 'null'))
const columns = (page: Page) => page.getByRole('combobox', { name: 'Breadboard columns' })
const rows = (page: Page) => page.getByRole('combobox', { name: 'Breadboard rows' })

test('resize, undo, export, import and recovery preserve board size and existing wiring', async ({ page }) => {
  await page.goto('/')
  await expect(columns(page)).toHaveValue('30')
  await expect.poll(() => recovered(page)).not.toBeNull()
  const original = await recovered(page)
  await columns(page).selectOption('60')
  await rows(page).selectOption('3')
  await expect(terminal(page, 'r3:j60')).toHaveCount(1)
  await expect.poll(async () => (await recovered(page)).board).toEqual({ columns: 60, rows: 3 })
  expect((await recovered(page)).parts).toEqual(original.parts)
  expect((await recovered(page)).wires).toEqual(original.wires)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(rows(page)).toHaveValue('1')
  await expect(terminal(page, 'r3:j60')).toHaveCount(0)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(rows(page)).toHaveValue('3')
  await page.getByRole('button', { name: 'Fit workbench', exact: true }).click()
  await terminal(page, 'r3:j60').scrollIntoViewIfNeeded()
  await expect(terminal(page, 'r3:j60')).toBeInViewport()
  await terminal(page, 'eg').scrollIntoViewIfNeeded()
  await expect(terminal(page, 'eg')).toBeInViewport()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit', exact: true }).click()
  const download = await downloadPromise
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await expect(columns(page)).toHaveValue('60')
  await expect(rows(page)).toHaveValue('3')
  await page.locator('input[type="file"]').setInputFiles((await download.path())!)
  await expect.poll(async () => (await recovered(page)).parts).toEqual(original.parts)
  await page.reload()
  await expect(columns(page)).toHaveValue('60')
  await expect(rows(page)).toHaveValue('3')
  await expect(terminal(page, 'r3:j60')).toHaveCount(1)
})

test('added rows support keyboard placement, movement, wiring, probes and safe shrinking', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await columns(page).selectOption('45')
  await rows(page).selectOption('2')
  await page.getByRole('complementary', { name: 'Parts library' }).getByRole('button', { name: /Resistor/ }).click()
  await terminal(page, 'r2:a40').focus()
  await terminal(page, 'r2:a40').press('Enter')
  await expect.poll(async () => (await recovered(page)).parts[0]?.pins).toEqual(['r2:a40', 'r2:a43'])
  await page.getByRole('button', { name: 'Select tool', exact: true }).click()
  await page.locator('[data-part="R1"]').focus()
  await page.locator('[data-part="R1"]').press('ArrowRight')
  await expect.poll(async () => (await recovered(page)).parts[0]?.pins).toEqual(['r2:a41', 'r2:a44'])
  await page.getByRole('button', { name: 'Wire tool', exact: true }).click()
  await terminal(page, 'b41').focus()
  await terminal(page, 'b41').press('Enter')
  await terminal(page, 'r2:b41').focus()
  await terminal(page, 'r2:b41').press('Enter')
  await expect.poll(async () => (await recovered(page)).wires[0]?.to).toBe('r2:b41')
  await rows(page).selectOption('1')
  await expect(rows(page)).toHaveValue('2')
  await expect(page.locator('.toast')).toContainText('Cannot shrink')
  await columns(page).selectOption('30')
  await expect(columns(page)).toHaveValue('45')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await page.keyboard.press('1')
  await terminal(page, 'r2:j45').focus()
  await terminal(page, 'r2:j45').press('Enter')
  await expect.poll(async () => (await recovered(page)).probes.CH1).toBe('r2:j45')
  await rows(page).selectOption('1')
  await expect(rows(page)).toHaveValue('2')
  await expect(page.locator('.toast')).toContainText('R2:J45')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await rows(page).selectOption('1')
  await columns(page).selectOption('30')
  await expect(rows(page)).toHaveValue('1')
  await expect(columns(page)).toHaveValue('30')
  expect(errors).toEqual([])
})

test('Pico dock and all breadboard rows fit without overlapping on the widest layout', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Load example' }).selectOption('pico-led')
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await columns(page).selectOption('60')
  await rows(page).selectOption('3')
  await page.getByRole('button', { name: 'Fit workbench', exact: true }).click()
  const right = Number(await terminal(page, 'a60').getAttribute('cx'))
  const pico = Number(await terminal(page, 'pico:1').getAttribute('cx'))
  expect(pico).toBeGreaterThan(right + 100)
  await expect(terminal(page, 'pico:1')).toBeInViewport()
  await terminal(page, 'r3:bn60').scrollIntoViewIfNeeded()
  await expect(terminal(page, 'r3:bn60')).toBeInViewport()
  await page.screenshot({ path: '/tmp/labor-large-breadboard.png' })
})


test('dragging between added rows and moving a lead each make one undoable edit', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 2200 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await columns(page).selectOption('60')
  await rows(page).selectOption('3')
  await page.getByRole('button', { name: 'Fit workbench', exact: true }).click()
  await page.getByRole('complementary', { name: 'Parts library' }).getByRole('button', { name: /Resistor/ }).click()
  await terminal(page, 'r2:a40').click()
  await page.getByRole('button', { name: 'Select tool', exact: true }).click()
  const part = page.locator('[data-part="R1"]')
  const drag = await part.evaluate(element => {
    const matrix = element.closest('svg')!.getScreenCTM()!
    const origin = new DOMPoint(100 + 40.5 * 24, 170 + 480).matrixTransform(matrix)
    const destination = new DOMPoint(100 + 40.5 * 24, 170 + 960).matrixTransform(matrix)
    return { x: origin.x, y: origin.y, toX: destination.x, toY: destination.y }
  })
  await page.mouse.move(drag.x, drag.y)
  await page.mouse.down()
  await page.mouse.move(drag.toX, drag.toY, { steps: 10 })
  await page.mouse.up()
  await expect.poll(async () => (await recovered(page)).parts[0]?.pins).toEqual(['r3:a40', 'r3:a43'])
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await recovered(page)).parts[0]?.pins).toEqual(['r2:a40', 'r2:a43'])
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await part.focus()
  await page.getByRole('complementary', { name: 'Inspector' }).getByRole('button', { name: 'Move R1 lead 2', exact: true }).click()
  await terminal(page, 'r3:a44').click()
  await expect.poll(async () => (await recovered(page)).parts[0]?.pins).toEqual(['r3:a40', 'r3:a44'])
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await recovered(page)).parts[0]?.pins).toEqual(['r3:a40', 'r3:a43'])
})


for (const screen of [{ width: 1440, height: 1120 }, { width: 700, height: 900 }]) {
  test(`adding rows grows the board area without shrinking holes at ${screen.width}px`, async ({ page }) => {
    await page.setViewportSize(screen)
    await page.goto('/')
    const viewport = page.getByTestId('board-viewport')
    const geometry = () => viewport.evaluate(element => ({
      height: element.clientHeight,
      scale: element.querySelector('svg')!.getScreenCTM()!.a,
      zoom: element.getAttribute('data-zoom'),
    }))
    for (const width of ['30', '60']) {
      await rows(page).selectOption('1')
      await columns(page).selectOption(width)
      await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
      const original = await geometry()
      for (const count of ['2', '3']) {
        await rows(page).selectOption(count)
        await expect.poll(async () => (await geometry()).height).toBeGreaterThan(original.height * Number(count) * 0.85)
        await expect.poll(async () => Math.abs((await geometry()).scale - original.scale)).toBeLessThan(0.002)
        expect((await geometry()).zoom).toBe(original.zoom)
      }
      await page.getByRole('button', { name: 'Undo', exact: true }).click()
      await expect(rows(page)).toHaveValue('2')
      await rows(page).selectOption('1')
      await expect.poll(async () => Math.abs((await geometry()).height - original.height)).toBeLessThanOrEqual(1)
    }
  })
}
