import { expect, test, type Page } from '@playwright/test'

const library = (page: Page) => page.getByRole('complementary', { name: 'Parts library', exact: true })
const inspector = (page: Page) => page.getByRole('complementary', { name: 'Inspector', exact: true })
const terminal = (page: Page, id: string) => page.getByRole('button', { name: new RegExp(`^${id.toUpperCase()}, (?:available|occupied)$`) })
const recovered = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1') ?? 'null'))
const ready = (page: Page) => expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'ready', { timeout: 45_000 })

async function create(page: Page, name: string, kind = 'resistor') {
  await library(page).getByRole('button', { name: 'Create custom component' }).click()
  const editor = page.getByRole('dialog', { name: 'Create custom component' })
  await editor.getByRole('combobox', { name: 'Base component' }).selectOption(kind)
  await editor.getByRole('textbox', { name: 'Model name' }).fill(name)
  await editor.getByRole('button', { name: 'Save model' }).click()
}

test('keyboard drafts, validation, cancellation, shared edits, copies and undo preserve model identity', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await ready(page)
  await library(page).getByRole('button', { name: 'Create custom component' }).focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('textbox', { name: 'Model name' })).toBeFocused()
  await dialog.getByRole('textbox', { name: 'Model name' }).fill('Current-sensitive resistor')
  await dialog.getByRole('spinbutton', { name: 'Row 1 value' }).fill('1')
  await dialog.getByRole('spinbutton', { name: 'Row 2 axis' }).fill('0')
  await expect(dialog.getByRole('button', { name: 'Save model' })).toBeDisabled()
  await expect(dialog.getByRole('alert')).toContainText('Row 2')
  await dialog.getByRole('spinbutton', { name: 'Row 2 axis' }).fill('10')
  await dialog.getByRole('spinbutton', { name: 'Row 2 value' }).fill('4')
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await expect.poll(async () => (await recovered(page)).customComponents?.length).toBe(1)
  await page.locator('[data-part="R1"]').focus()
  await inspector(page).getByRole('combobox', { name: 'Component model' }).selectOption({ label: 'Current-sensitive resistor' })
  await expect(inspector(page).getByRole('spinbutton', { name: 'Resistance', exact: true })).toHaveCount(0)
  await ready(page)
  await inspector(page).getByRole('button', { name: 'Edit model', exact: true }).click()
  await expect(dialog).toContainText('Saving updates 1 placed instance')
  await dialog.getByRole('spinbutton', { name: 'Row 1 value' }).fill('2')
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(inspector(page)).toContainText('1 kΩ nominal')
  await inspector(page).getByRole('button', { name: 'Edit model', exact: true }).click()
  await dialog.getByRole('spinbutton', { name: 'Row 1 value' }).fill('2')
  await page.screenshot({ path: '/tmp/labor-custom-editor.png' })
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await expect(inspector(page)).toContainText('2 kΩ nominal')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(inspector(page)).toContainText('1 kΩ nominal')
  await inspector(page).getByRole('button', { name: 'Make independent copy' }).click()
  await expect(inspector(page).getByRole('heading', { name: 'Current-sensitive resistor (copy)' })).toBeVisible()
  await expect.poll(async () => (await recovered(page)).customComponents.length).toBe(2)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(inspector(page).getByRole('heading', { name: 'Current-sensitive resistor', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('distinct same-kind click/drag placement, lead edits, clear, recovery, export and fresh import', async ({ page, browser }) => {
  await page.goto('/')
  await library(page).getByRole('button', { name: 'Clear board', exact: true }).click()
  await create(page, 'Model A')
  await terminal(page, 'a5').click()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-part="R1"]')).toHaveAttribute('aria-label', /Model A/)
  await create(page, 'Model B')
  await library(page).getByRole('button', { name: 'Model B', exact: true }).dragTo(terminal(page, 'a15'))
  await page.keyboard.press('Escape')
  await expect.poll(async () => (await recovered(page)).parts.length).toBe(2)
  await page.locator('[data-part="R2"]').focus()
  await inspector(page).getByRole('button', { name: 'Move R2 lead 2', exact: true }).click()
  await terminal(page, 'a20').click()
  await expect.poll(async () => (await recovered(page)).parts[1].pins[1]).toBe('a20')
  const doc = await recovered(page)
  expect(doc.parts[0].customModelId).not.toBe(doc.parts[1].customModelId)
  await page.reload()
  await expect(library(page).getByRole('button', { name: 'Model A', exact: true })).toBeVisible()
  await expect(page.locator('[data-part="R2"]')).toHaveAttribute('aria-label', /Model B/)
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit' }).click()
  const download = await downloadEvent
  const filePath = await download.path()
  const context = await browser.newContext()
  const fresh = await context.newPage(); await fresh.goto('/')
  await fresh.locator('input[type=file]').setInputFiles(filePath!)
  await expect.poll(async () => (await recovered(fresh))?.customComponents?.length).toBe(2)
  await expect(fresh.locator('[data-part="R1"]')).toHaveAttribute('aria-label', /Model A/)
  await context.close()
  await library(page).getByRole('button', { name: 'Clear board', exact: true }).click()
  await expect(page.locator('[data-part]')).toHaveCount(0)
  await expect(library(page).getByRole('button', { name: 'Model B', exact: true })).toBeVisible()
  await library(page).getByRole('button', { name: 'Delete Model B', exact: true }).click()
  await expect(library(page).getByRole('button', { name: 'Model B', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(library(page).getByRole('button', { name: 'Model B', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('[data-part]')).toHaveCount(2)
})

test('capacitor models show frozen nonlinear readings and survive adding a Pico', async ({ page }) => {
  await page.goto('/')
  await create(page, 'Voltage-sensitive capacitor', 'capacitor')
  await page.locator('[data-part="C1"]').focus()
  await inspector(page).getByRole('combobox', { name: 'Component model' }).selectOption({ label: 'Voltage-sensitive capacitor' })
  await inspector(page).getByRole('button', { name: 'Edit model', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('spinbutton', { name: 'Row 1 value' }).fill('50')
  await dialog.getByRole('spinbutton', { name: 'Row 3 value' }).fill('200')
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await ready(page)
  await expect(inspector(page).getByLabel('Recorded model value')).toHaveText(/nF/)
  await expect(inspector(page).getByLabel('Recorded stored energy')).toBeVisible()
  await library(page).getByRole('button', { name: 'Raspberry Pi Pico', exact: true }).click()
  await expect.poll(async () => (await recovered(page)).schemaVersion).toBe(3)
  await expect.poll(async () => (await recovered(page)).pico).toBeTruthy()
})

test('nonlinear DC readings, stale edits, long names and example replacement undo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Load example' }).selectOption('custom-resistance')
  await ready(page)
  await page.locator('[data-part="R1"]').focus()
  const pane = inspector(page)
  // Switch the source to DC using the portable document, preserving the same model.
  const doc = await recovered(page)
  doc.wires[0].from = 'cv'
  await page.locator('input[type=file]').setInputFiles({ name: 'custom-dc.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(doc)) })
  await ready(page)
  await page.locator('[data-part="R1"]').click()
  await expect(pane.getByLabel('DC current 1 → 2', { exact: true })).toHaveText(/2\.071 mA/)
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Auto update', exact: true }).uncheck()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await pane.getByRole('button', { name: 'Edit model', exact: true }).click()
  const dialog = page.getByRole('dialog')
  const name = 'A long custom resistor name '.repeat(3).slice(0, 80)
  await dialog.getByRole('textbox', { name: 'Model name' }).fill(name)
  await dialog.getByRole('spinbutton', { name: 'Row 1 value' }).fill('1.1')
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'stale')
  await expect(pane.getByLabel('DC current 1 → 2', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(pane.getByRole('heading', { name: 'Current-sensitive resistor', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Load example' }).selectOption('rc-filter')
  await expect(library(page).getByRole('button', { name: 'Current-sensitive resistor', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(library(page).getByRole('button', { name: 'Current-sensitive resistor', exact: true })).toBeVisible()
})

test('storage failure preserves custom models in memory and export, and mobile editor fits', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError') } })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await library(page).getByRole('button', { name: 'Create custom component' }).click()
  const dialog = page.getByRole('dialog')
  const bounds = await dialog.boundingBox()
  expect(bounds!.width).toBeLessThanOrEqual(390)
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  await dialog.getByRole('textbox', { name: 'Model name' }).fill('Survives storage failure')
  await page.screenshot({ path: '/tmp/labor-custom-editor-mobile.png' })
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await expect(library(page).getByRole('button', { name: 'Survives storage failure', exact: true })).toBeVisible()
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit' }).click()
  const stream = await (await event).createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(chunk)
  expect(JSON.parse(Buffer.concat(chunks).toString()).customComponents[0].name).toBe('Survives storage failure')
})
