import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('documentation composes, links, reorders, recovers, and exports without invalidating a capture', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'ready')
  await page.getByRole('tab', { name: 'Documentation', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'Documentation', exact: true })
  await expect(panel).toContainText('How it works and why')
  await expect(panel).toContainText('159 Hz')
  await page.screenshot({ path: testInfo.outputPath('documentation-reader.png'), fullPage: true })
  await panel.getByRole('button', { name: 'Edit documentation', exact: true }).click()
  await panel.getByLabel('Section type', { exact: true }).selectOption('component')
  await panel.getByRole('button', { name: 'Add section', exact: true }).click()
  await panel.getByLabel('Section title', { exact: true }).fill('My capacitor experiment')
  await panel.getByLabel('Linked component', { exact: true }).selectOption('C1')
  await panel.getByLabel('Section notes', { exact: true }).fill('A larger capacitor lowers the corner frequency.\nCompare the phase shift.')
  await panel.getByRole('button', { name: 'Move section up', exact: true }).click()
  await expect(panel.getByRole('navigation', { name: 'Documentation sections' }).getByRole('button').nth(6)).toContainText('My capacitor experiment')
  await page.screenshot({ path: testInfo.outputPath('documentation-editor.png'), fullPage: true })
  await panel.getByRole('button', { name: 'Delete section', exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(panel.getByRole('navigation', { name: 'Documentation sections' })).toContainText('My capacitor experiment')
  await expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'ready')
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!).documentation.sections.some((s: { title: string }) => s.title === 'My capacitor experiment'))).toBe(true)
  const projectDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit', exact: true }).click()
  const project = await readFile((await (await projectDownload).path())!, 'utf8')
  expect(JSON.parse(project).documentation.sections.some((s: { title: string }) => s.title === 'My capacitor experiment')).toBe(true)
  await page.reload()
  await page.getByRole('tab', { name: 'Documentation', exact: true }).click()
  await expect(panel).toContainText('My capacitor experiment')
  for (const [label, extension] of [['Export Markdown', 'md'], ['Export HTML', 'html']]) {
    const downloadPromise = page.waitForEvent('download')
    await panel.getByRole('button', { name: label, exact: true }).click()
    const download = await downloadPromise
    expect(download.suggestedFilename()).toBe(`rc-low-pass-filter-documentation.${extension}`)
    const output = await readFile((await download.path())!, 'utf8')
    expect(output).toContain('My capacitor experiment')
    expect(output).toContain('Components and pin connections')
    expect(output).toContain('W1: osc → b6')
  }
  await page.getByLabel('Load example').selectOption('voltage-divider')
  await page.locator('input[type="file"]').setInputFiles({ name: 'documented-circuit.json', mimeType: 'application/json', buffer: Buffer.from(project) })
  await page.getByRole('tab', { name: 'Documentation', exact: true }).click()
  await expect(panel).toContainText('My capacitor experiment')
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.getByRole('button', { name: 'Edit documentation', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('documentation-mobile.png'), fullPage: true })
})
