import { expect, test } from '@playwright/test'

test('synth examples load by difficulty, capture, and expose hardware build notes', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const select = page.getByRole('combobox', { name: 'Load example' })
  await expect(select.locator('optgroup')).toHaveCount(3)
  await expect(select.locator('option')).toHaveCount(21)
  for (const id of ['cv-attenuator', 'ac-coupling', 'gate-to-trigger', 'envelope-follower', 'cv-mixer', 'attenuverter', 'sallen-key-filter']) {
    await select.selectOption(id)
    await expect(page.getByText('CAPTURED', { exact: true })).toBeVisible({ timeout: 45_000 })
    await expect(page.locator('.diagnostic, .error-copy')).toHaveCount(0)
    await expect(page.locator('.experiment-card h3')).toHaveText(await select.locator('option:checked').innerText())
    await page.getByRole('region', { name: 'Breadboard view', exact: true }).screenshot({ path: testInfo.outputPath(`${id}-board.png`) })
  }
  const lesson = page.locator('.experiment-card')
  await expect(lesson.locator('.eyebrow')).toContainText('Advanced')
  await lesson.getByText('What to try', { exact: true }).click()
  await expect(lesson).toContainText('4.7')
  await lesson.getByText('Build on EDU LABOR', { exact: true }).click()
  await expect(lesson).toContainText('TL072')
  await expect(lesson.locator('.experiment-parts')).toContainText('TL072-style dual op-amp')
  await expect(lesson.getByRole('link', { name: 'LABOR manual' })).toHaveAttribute('href', /ericasynths/)
  await page.screenshot({ path: testInfo.outputPath('sallen-key-example.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(select).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('synth-examples-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('a synth example remains editable, restorable, and recoverable', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('cv-attenuator')
  const wiper = page.getByRole('spinbutton', { name: 'Wiper percentage', exact: true })
  await expect(wiper).toHaveValue('50')
  await wiper.fill('25')
  await wiper.press('Tab')
  await expect(page.getByText('CAPTURED', { exact: true })).toBeVisible()
  await page.locator('.operating-point-panel > summary').click()
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('1.250 V')
  await page.getByRole('button', { name: 'Restore example', exact: true }).click()
  await expect(wiper).toHaveValue('50')
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('2.500 V')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(wiper).toHaveValue('25')
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1') ?? '{}').parts?.[0]?.position)).toBe(0.25)
  await page.reload()
  await expect(page.getByLabel('Load example')).toHaveValue('cv-attenuator')
  await expect(page.getByText('CAPTURED', { exact: true })).toBeVisible()
  await page.locator('[data-part="P1"]').focus()
  await expect(wiper).toHaveValue('25')
})
