import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

async function captured(page: Page) {
  await expect(page.getByText('CAPTURED', { exact: true })).toBeVisible({ timeout: 45_000 })
}

test('the DC meter and component currents follow the solved circuit and clear on stale edits', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('voltage-divider')
  await captured(page)
  await page.locator('.operating-point-panel > summary').click()
  await expect(page.getByLabel('CH1 DC voltage', { exact: true })).toHaveText('5.000 V')
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('2.500 V')
  await expect(page.getByLabel('DC differential voltage', { exact: true })).toHaveText('2.500 V')
  await page.locator('[data-part="R1"]').focus()
  await expect(page.getByLabel('DC current 1 → 2', { exact: true })).toHaveText('250.000 µA')
  await expect(page.getByLabel('DC component power', { exact: true })).toHaveText('625.000 µW')
  await page.getByText('Auto update', { exact: true }).click()
  const resistance = page.getByRole('spinbutton', { name: 'Resistance', exact: true })
  await resistance.fill('20')
  await resistance.press('Tab')
  await expect(page.getByText('NEEDS SIMULATION', { exact: true })).toBeVisible()
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('—')
  await expect(page.getByLabel('DC component power', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Capture', exact: true }).click()
  await captured(page)
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('1.667 V')
  await expect(page.getByLabel('DC current 1 → 2', { exact: true })).toHaveText('166.667 µA')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Capture', exact: true }).click()
  await captured(page)
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('2.500 V')
})

test('the decay envelope is a real editable source; Fire preserves document history', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('envelope-shaping')
  await captured(page)
  await page.locator('.operating-point-panel > summary').click()
  await expect(page.getByLabel('CH1 DC voltage', { exact: true })).toHaveText('0.000 V')
  await page.locator('.scope-measurements > summary').click()
  await page.getByRole('spinbutton', { name: 'Cursor A milliseconds' }).fill('21.001')
  const ch1AtA = page.getByRole('table', { name: 'Channel measurements' }).getByRole('row', { name: /^At cursor A/ }).getByRole('cell').first()
  expect(parseFloat(await ch1AtA.innerText())).toBeCloseTo(5 / Math.E, 1)
  const decay = page.getByRole('spinbutton', { name: 'Envelope decay', exact: true })
  await decay.fill('5')
  await decay.press('Tab')
  await captured(page)
  expect(parseFloat(await ch1AtA.innerText())).toBeLessThan(0.1)
  await page.getByRole('button', { name: 'Fire envelope', exact: true }).click()
  await captured(page)
  expect(parseFloat(await ch1AtA.innerText())).toBeLessThan(0.1)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(decay).toHaveValue('20')
  await captured(page)
  expect(parseFloat(await ch1AtA.innerText())).toBeCloseTo(5 / Math.E, 1)
  expect(errors).toEqual([])
  const notice = page.getByRole('button', { name: 'Dismiss notification', exact: true })
  if (await notice.isVisible()) await notice.click()
  await page.screenshot({ path: testInfo.outputPath('envelope-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Fire envelope', exact: true }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('envelope-mobile.png'), fullPage: true })
})

test('gate level solves at DC, trigger stays initially low, and settings survive recovery', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('envelope-shaping')
  await captured(page)
  await page.locator('.operating-point-panel > summary').click()
  await page.getByLabel('Envelope mode', { exact: true }).selectOption('gate')
  await captured(page)
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('0.000 V')
  await page.getByRole('button', { name: 'Gate high', exact: true }).click()
  await captured(page)
  await expect(page.getByLabel('CH1 DC voltage', { exact: true })).toHaveText('5.000 V')
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toHaveText('5.000 V')
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1') ?? '{}').instruments?.envelope?.gateHigh)).toBe(true)
  await page.reload()
  await captured(page)
  await expect(page.getByLabel('Envelope mode', { exact: true })).toHaveValue('gate')
  await expect(page.getByRole('button', { name: 'Gate high', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Envelope mode', { exact: true }).selectOption('trigger')
  await captured(page)
  await page.locator('.operating-point-panel > summary').click()
  await expect(page.getByLabel('CH1 DC voltage', { exact: true })).toHaveText('0.000 V')
  await page.locator('.scope-measurements > summary').click()
  const readings = page.getByRole('table', { name: 'Channel measurements' }).getByRole('row', { name: /^At cursor A/ }).getByRole('cell').first()
  await page.getByRole('spinbutton', { name: 'Cursor A milliseconds' }).fill('1.5')
  expect(parseFloat(await readings.innerText())).toBeGreaterThan(4.95)
  await page.getByRole('spinbutton', { name: 'Cursor A milliseconds' }).fill('2.5')
  expect(Math.abs(parseFloat(await readings.innerText()))).toBeLessThan(0.05)
})
