import { expect, test } from '@playwright/test'
const fixture = 'tests/fixtures/kicad/divider.kicad_sch'

test('reviews matches, searches for unknown components, imports and undoes atomically', async ({ page }) => {
  await page.goto('/')
  const title = await page.locator('.project-title').textContent()
  await page.locator('input[type=file]').setInputFiles(fixture)
  const dialog = page.getByRole('dialog', { name: 'Review KiCad import' })
  await expect(dialog).toBeVisible()
  await expect(page.locator('.project-title')).toHaveText(title!)
  await expect(dialog.getByRole('button', { name: 'Confirm and import' })).toBeDisabled()
  await expect(dialog.getByLabel('Component for R1', { exact: true })).toHaveValue('resistor')
  await dialog.getByLabel('Search matches for R2').fill('resistor')
  await dialog.getByLabel('Component for R2', { exact: true }).selectOption('resistor')
  await expect(dialog.getByLabel('Value for R2')).toHaveValue('4700')
  await dialog.getByLabel('R2 pin 2', { exact: true }).selectOption('1')
  await dialog.getByRole('button', { name: 'Confirm and import' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Map every KiCad pin exactly once')
  await dialog.getByLabel('R2 pin 2', { exact: true }).selectOption('2')
  await dialog.getByLabel('Source for GND').selectOption('gnd')
  await dialog.getByLabel('Source for VCC').selectOption('cv')
  await dialog.getByRole('button', { name: 'Confirm and import' }).click()
  await expect(dialog).toBeHidden()
  await expect(page.locator('.project-title')).toContainText('Imported divider')
  await expect(page.locator('[data-part]')).toHaveCount(2)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.project-title')).toHaveText(title!)
})

test('cancel, Escape, repeated file selection and malformed input preserve the current project', async ({ page }) => {
  await page.goto('/')
  const title = await page.locator('.project-title').textContent()
  await page.locator('input[type=file]').setInputFiles(fixture)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.locator('input[type=file]').setInputFiles(fixture)
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.locator('input[type=file]').setInputFiles({ name: 'bad.kicad_sch', mimeType: 'text/plain', buffer: Buffer.from('(kicad_sch') })
  await expect(page.locator('.project-title')).toHaveText(title!)
  await expect(page.getByRole('dialog')).toBeHidden()
})

test('review remains usable on mobile and keeps keyboard focus inside the dialog', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.locator('input[type=file]').setInputFiles(fixture)
  const dialog = page.getByRole('dialog', { name: 'Review KiCad import' })
  await expect(dialog).toBeVisible()
  const bounds = await dialog.boundingBox()
  expect(bounds!.width).toBeLessThanOrEqual(390)
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy()
  await dialog.getByLabel('Search matches for R2').fill('capacitor')
  await page.keyboard.press('Control+z')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel KiCad import' }).focus()
  await page.keyboard.press('Tab')
  await expect(dialog.getByLabel('Search matches for R1')).toBeFocused()
  await page.screenshot({ path: '/tmp/labor-kicad-import-mobile.png' })
})
