import { expect, test } from '@playwright/test'

test('OLED library, Pico firmware and scrubbable display frames', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Find a component').fill('oled')
  await expect(page.getByRole('button', { name: 'SSD1306 OLED display', exact: true })).toBeVisible()
  await page.getByLabel('Load example').selectOption('pico-oled')
  await expect(page.getByText('IntelliSense ready', { exact: true })).toBeVisible({ timeout: 45000 })
  await expect(page.getByText('Problems (0)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Run · 1 s', exact: true }).click()
  await expect(page.getByText('Capture ready', { exact: true })).toBeVisible({ timeout: 30000 })
  await expect(page.getByLabel('Pico serial console')).toContainText('OLED frame 9')
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.getByRole('button', { name: 'Recording end', exact: true }).click()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await expect(page.locator('[data-oled="OLED1"]')).toHaveAttribute('data-oled-state', 'on')
  const last = await page.locator('[data-oled="OLED1"] [data-oled-pixels]').getAttribute('d')
  expect(last!.length).toBeGreaterThan(1000)
  await page.getByRole('region', { name: 'Breadboard view', exact: true }).screenshot({ path: testInfo.outputPath('oled-board.png') })
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.getByLabel('Recording time milliseconds', { exact: true }).fill('150')
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await expect(page.locator('[data-oled="OLED1"] [data-oled-pixels]')).not.toHaveAttribute('d', last!)
  await expect(page.locator('[data-oled="OLED1"]')).toHaveAttribute('data-oled-state', 'on')
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.getByRole('button', { name: 'Recording start', exact: true }).click()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await expect(page.locator('[data-oled="OLED1"]')).toHaveAttribute('data-oled-state', 'off')
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await expect(page.locator('[data-oled="OLED1"] [data-oled-pixels]')).toHaveAttribute('d', '')
  await page.reload()
  await expect(page.getByRole('tab', { name: 'Circuit', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('[data-part="OLED1"]')).toBeVisible()
  await expect(page.locator('[data-oled="OLED1"]')).toHaveAttribute('data-oled-state', 'off')
  expect(errors).toEqual([])
})

test('OLED can be placed from the catalog and moved with its four pins', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await page.getByLabel('Component category').selectOption('displays')
  await page.getByRole('button', { name: 'SSD1306 OLED display', exact: true }).click()
  await page.getByRole('button', { name: 'E14, available', exact: true }).click()
  await page.getByRole('button', { name: 'Rotate placement', exact: true }).click()
  await page.getByRole('button', { name: 'F24, available', exact: true }).click()
  await expect(page.locator('[data-part="OLED2"] > title')).toContainText('SDA at F21')
  await page.getByRole('button', { name: 'Select tool', exact: true }).click()
  const part = page.locator('[data-part="OLED1"]')
  await expect(part.locator('[data-pin]')).toHaveCount(4)
  await part.focus()
  await part.press('ArrowRight')
  await expect(part.locator(':scope > title')).toContainText('GND at E15')
  await expect(part.locator(':scope > title')).toContainText('SDA at E18')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(part.locator(':scope > title')).toContainText('GND at E14')
})
