import { expect, test } from '@playwright/test'

test('Overview keeps circuit context out of Inspector and inspects the current parts inventory', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'ready', { timeout: 45_000 })
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  await expect(inspector.getByRole('heading', { name: 'Capacitor', exact: true })).toBeVisible()
  await expect(inspector.getByRole('region', { name: 'Example guide', exact: true })).toHaveCount(0)
  await expect(inspector.getByRole('region', { name: 'Circuit checks', exact: true })).toHaveCount(0)
  await expect(inspector.getByText('Generated netlist', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: 'Toggle inspector', exact: true }).click()
  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  const overview = page.getByRole('tabpanel', { name: 'Overview', exact: true })
  const parts = overview.getByRole('table', { name: 'Circuit parts', exact: true })
  const capacitor = parts.getByRole('row').filter({ has: page.getByRole('button', { name: 'Inspect C1', exact: true }) })
  await expect(parts.getByRole('row')).toHaveCount(3)
  await expect(capacitor).toContainText('100 nF')
  await expect(overview.getByRole('region', { name: 'Example guide', exact: true })).toBeVisible()
  await expect(overview.getByRole('region', { name: 'Circuit checks', exact: true })).toBeVisible()
  await expect(inspector).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('overview-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('overview-phone.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1120 })

  await capacitor.getByRole('button', { name: 'Inspect C1', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('tab', { name: 'Circuit', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('[data-part="C1"]')).toBeFocused()
  await expect(inspector.getByRole('heading', { name: 'Capacitor', exact: true })).toBeVisible()
  await inspector.getByRole('button', { name: '220', exact: true }).click()
  await expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'ready', { timeout: 45_000 })

  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  await expect(capacitor).toContainText('220 nF')
  await overview.getByText('Generated netlist', { exact: true }).click()
  await expect(overview.locator('.monaco-editor')).toBeVisible()
  await expect(overview.locator('.monaco-editor')).toContainText('C_C1')
  const netlist = overview.getByRole('textbox', { name: 'Generated SPICE netlist', exact: true })
  await expect(netlist).toHaveAttribute('readonly', 'true')
  await netlist.focus()
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Control+k')
  await page.keyboard.press('Control+i')
  await expect(page.locator('.monaco-hover')).toContainText('Independent voltage source')
  await page.keyboard.press('Escape')
  const colors = await overview.locator('.view-lines span[class^="mtk"]').evaluateAll(spans => [...new Set(spans.map(span => getComputedStyle(span).color))])
  expect(colors.length).toBeGreaterThan(2)
  await netlist.focus()
  await page.keyboard.press('Tab')
  await expect(netlist).not.toBeFocused()
  await overview.getByText('Generated netlist', { exact: true }).click()
  await expect(overview.locator('.monaco-editor')).toHaveCount(0)
  await overview.getByText('Generated netlist', { exact: true }).click()
  await expect(overview.locator('.monaco-editor')).toContainText('C_C1')
  await overview.getByRole('button', { name: 'View results', exact: true }).click()
  await expect(page.getByRole('tab', { name: 'Results', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('region', { name: 'Oscilloscope', exact: true })).toBeVisible()
})

test('a cleared board has an actionable custom-circuit overview without stale example content', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  const overview = page.getByRole('tabpanel', { name: 'Overview', exact: true })
  await expect(overview).toContainText('No components yet.')
  await expect(overview).toContainText('0 parts')
  await expect(overview.getByRole('region', { name: 'Example guide', exact: true }).getByRole('heading', { name: 'Custom circuit', exact: true })).toBeVisible()
  await expect(overview.getByRole('button', { name: 'Restore example', exact: true })).toHaveCount(0)
  await expect(overview.getByRole('button', { name: /^Inspect / })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('overview-empty.png'), fullPage: true })
  await overview.getByRole('button', { name: 'Open circuit', exact: true }).click()
  await expect(page.getByRole('tab', { name: 'Circuit', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('board-viewport')).toBeVisible()
})

test('netlist updates with the circuit and navigates to model definitions', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  await page.getByText('Generated netlist', { exact: true }).click()
  const viewer = page.locator('.overview-netlist-editor')
  await expect(viewer).toContainText('C_C1')
  await page.getByLabel('Load example').selectOption('diode-clipper')
  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  await expect(viewer).toContainText('D_D1')
  const editor = page.getByRole('textbox', { name: 'Generated SPICE netlist', exact: true })
  await editor.focus()
  await page.keyboard.press('Control+f')
  await page.keyboard.insertText('D_D1')
  await page.keyboard.press('Escape')
  await page.keyboard.press('End')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('F12')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Control+k')
  await page.keyboard.press('Control+i')
  await expect(page.locator('.monaco-hover')).toContainText('Device model definition')
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
