import { expect, test } from '@playwright/test'
test('Monaco hover can extend above the editor without being clipped', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('pico-led')
  await expect(page.getByText('IntelliSense ready', { exact: true })).toBeVisible({ timeout: 45000 })
  await page.locator('.pico-editor').scrollIntoViewIfNeeded()
  const editor = page.getByRole('textbox', { name: 'Pico main.py editor' })
  await editor.focus()
  await page.keyboard.press('Control+Home')
  for (let line = 0; line < 3; line++) await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Control+k')
  await page.keyboard.press('Control+i')
  const hover = page.locator('.monaco-hover').filter({ hasText: 'print' }).first()
  await expect(hover).toBeVisible()
  await expect.poll(() => hover.evaluate(element => {
    const rect = element.getBoundingClientRect()
    const editorTop = document.querySelector('.pico-editor')!.getBoundingClientRect().top
    const hit = document.elementFromPoint(rect.left + rect.width / 2, rect.top + 8)
    return rect.top < editorTop && !!hit && element.contains(hit)
  })).toBe(true)
})

test('Pico PWM workflow, local assets, keyboard focus, stale edits and persistence', async ({ page, context }, testInfo) => {
  test.setTimeout(90_000)
  const external: string[] = [], errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await context.route('**/*', route => { if (new URL(route.request().url()).hostname !== '127.0.0.1') { external.push(route.request().url()); return route.abort() } return route.continue() })
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('pico-pwm')
  await expect(page.getByText('IntelliSense ready', { exact: true })).toBeVisible({ timeout: 45000 })
  await expect(page.getByLabel('Pico serial console')).toContainText('Use print() in your code, then Simulate to see serial output here.')
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pico pin 1 GP0', exact: false })).toBeVisible()
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await page.getByRole('button', { name: 'Run · 100 ms' }).click()
  await expect(page.getByText('Capture ready', { exact: true })).toBeVisible({ timeout: 30000 })
  await expect(page.getByLabel('Pico serial console')).toContainText('Pico PWM')
  const editor = page.getByRole('textbox', { name: 'Pico main.py editor' })
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.locator('.scope-measurements > summary').click()
  const mean = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Capture mean', exact: true }) }).getByRole('cell').nth(1)
  const before = parseFloat(await mean.innerText())
  const source = await page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!).pico.source)
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await editor.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText(source.replace('32768', '16384'))
  await page.getByRole('button', { name: 'Run · 100 ms' }).click()
  await expect(page.getByText('Capture ready', { exact: true })).toBeVisible({ timeout: 30000 })
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  const after = parseFloat(await mean.innerText())
  expect(after / before).toBeGreaterThan(.47)
  expect(after / before).toBeLessThan(.53)
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await editor.focus()
  await page.keyboard.press('Control+End')
  await page.keyboard.type('\n# wiring remains unchanged')
  await expect(page.getByText('Source or wiring changed — Run to capture', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Wire tool', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await page.getByRole('button', { name: 'Collapse editor', exact: true }).click()
  await page.getByRole('button', { name: 'Expand editor', exact: true }).click()
  await expect(page.locator('.pico-editor')).toBeVisible()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('labor-playground.document.v1'))).toContain('# wiring remains unchanged')
  await page.reload()
  await expect(page.getByRole('tab', { name: 'Circuit', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await expect(page.getByLabel('Pico serial console')).toContainText('Use print() in your code, then Simulate to see serial output here.')
  await page.screenshot({ path: testInfo.outputPath('pico-workbench.png'), fullPage: true })
  expect(external).toEqual([])
  expect(errors).toEqual([])
})

test('stub navigation is read-only; Stop, Reset and structural undo preserve source', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('pico-console')
  await expect(page.getByText('IntelliSense ready', { exact: true })).toBeVisible({ timeout: 45000 })
  const editor = page.getByRole('textbox', { name: 'Pico main.py editor' })
  await editor.focus(); await page.keyboard.press('Control+Home'); await page.keyboard.press('End'); await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('F12')
  await expect(page.locator('.pico-stub')).toContainText('machine.pyi · read only')
  await page.getByRole('button', { name: 'Back to main.py', exact: true }).click()
  await page.keyboard.press('Control+End'); await page.keyboard.insertText('\n# preserved draft')
  await expect.poll(() => page.evaluate(() => localStorage.getItem('labor-playground.document.v1'))).toContain('preserved draft')
  await page.getByRole('button', { name: 'Remove Pico', exact: true }).click()
  await expect(page.getByLabel('Pico programming')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('tab', { name: 'Pico Code', exact: true }).click()
  await expect(page.getByLabel('Pico programming')).toBeVisible()
  await expect(page.locator('.pico-editor')).toContainText('preserved draft')
  // Hold asset responses so cancellation is exercised during preparation.
  await page.route('**/pico/micropython.uf2', async route => { await new Promise(resolve => setTimeout(resolve, 1500)); await route.continue() })
  await page.getByRole('button', { name: 'Run · 100 ms' }).click()
  await page.getByRole('button', { name: 'Stop', exact: true }).click()
  await expect(page.getByText('Stopped', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reset', exact: true }).first().click()
  await expect(page.getByLabel('Pico serial console')).toContainText('Use print() in your code, then Simulate to see serial output here.')
  await expect(page.locator('.pico-editor')).toContainText('preserved draft')
})

test('language asset failure preserves editable source and retries without a reload', async ({ page }) => {
  let fail = true
  await page.route('**/pico/stubs.json', route => fail ? route.fulfill({ status: 503, body: 'Unavailable fixture' }) : route.continue())
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('pico-console')
  await expect(page.getByText(/Cannot load Pico asset stubs.json/)).toBeVisible()
  const editor = page.getByRole('textbox', { name: 'Pico main.py editor' })
  await editor.focus(); await page.keyboard.press('Control+End'); await page.keyboard.insertText('\n# retained during failure')
  fail = false
  await page.getByRole('button', { name: 'Retry analysis', exact: true }).click()
  await expect(page.getByText('IntelliSense ready', { exact: true })).toBeVisible({ timeout: 45000 })
  await expect(page.locator('.pico-editor')).toContainText('retained during failure')
  await page.getByRole('button', { name: 'Run · 100 ms' }).click()
  await expect(page.getByText('Capture ready', { exact: true })).toBeVisible()
})

test('runtime errors navigate to source and a corrected program recovers', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('pico-console')
  const editor = page.getByRole('textbox', { name: 'Pico main.py editor' })
  await editor.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('raise ValueError("fixture failure")\n')
  await page.getByRole('button', { name: 'Run · 100 ms' }).click()
  await expect(page.locator('.pico-error')).toContainText('fixture failure')
  await page.getByRole('button', { name: 'Go to line 1', exact: true }).click()
  await page.keyboard.press('Control+a'); await page.keyboard.insertText('print("recovered")\n')
  await page.getByRole('button', { name: 'Run · 100 ms' }).click()
  await expect(page.getByText('Capture ready', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Pico serial console')).toContainText('recovered')
  await expect(page.locator('.pico-error')).toHaveCount(0)
})
