import { expect, test } from '@playwright/test'

test('variables and logs example teaches both views on a shared recording', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('pico-state-logs')
  await expect(page.getByRole('tab', { name: 'Pico Code', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByText('IntelliSense ready', { exact: true })).toBeVisible({ timeout: 45_000 })
  await expect(page.getByText('Problems (0)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Run · 500 ms', exact: true }).click()
  await expect(page.getByText('Capture ready', { exact: true })).toBeVisible({ timeout: 45_000 })
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await expect(page.getByLabel('Time per division', { exact: true })).toHaveValue('50')
  const inspector = page.getByRole('region', { name: 'Pico application state', exact: true })
  const value = (name: string) => inspector.getByTestId(`pico-variable-state."${name}"`)
  const seek = (ms: string) => page.getByLabel('Recording time milliseconds').fill(ms)
  await seek('50')
  await page.getByLabel('Filter Pico variables').fill('state')
  await inspector.getByRole('button', { name: 'Expand state', exact: true }).click()
  await inspector.getByRole('button', { name: 'Expand state."history"', exact: true }).click()
  await expect(value('duty')).toHaveText('25')
  await expect(value('history')).toHaveText('1 items')
  await expect(value('ticks')).toHaveText('3')
  await expect(page.getByLabel('Pico log duty value', { exact: true })).toHaveText('25.000 %')
  await expect(page.getByLabel('Pico log target value', { exact: true })).toHaveText('0.825 V')
  await seek('90')
  await expect(value('ticks')).toHaveText('5')
  await expect(page.getByLabel('Pico log target value', { exact: true })).toHaveText('0.825 V')
  await seek('150')
  await expect(value('duty')).toHaveText('75')
  await expect(value('history')).toHaveText('2 items')
  await expect(page.getByLabel('Pico log target value', { exact: true })).toHaveText('2.475 V')
  const filterVoltage = parseFloat(await page.getByLabel('CH2 recorded voltage', { exact: true }).innerText())
  expect(filterVoltage).toBeGreaterThan(2.3)
  expect(filterVoltage).toBeLessThan(2.6)
  await inspector.screenshot({ path: testInfo.outputPath('example-state.png') })
  await page.getByRole('region', { name: 'Pico scope logs', exact: true }).screenshot({ path: testInfo.outputPath('example-logs.png') })
  await page.getByRole('button', { name: 'Recording end', exact: true }).click()
  await expect(value('phase')).toHaveText('"complete"')
  await expect(value('history')).toHaveText('4 items')
  await page.getByLabel('Filter Pico variables').fill('target_voltage')
  await expect(inspector).toContainText('No variables match')
  await expect(page.getByLabel('Pico log target waveform', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Example guide', exact: true })).toContainText('target_voltage')
  await page.getByRole('tab', { name: 'Documentation', exact: true }).click()
  await expect(page.getByRole('tabpanel', { name: 'Documentation', exact: true })).toContainText('scope.log()')
  expect(errors).toEqual([])
})
