import { test, expect } from '@playwright/test'
test('Pico compatibility spike: local semantic completion and worker execution', async ({ page }) => {
  test.setTimeout(90_000)
  page.on('pageerror', error => console.log('PAGE ERROR', error.message))
  await page.goto('/tests/pico-harness.html')
  await expect(page.locator('#status')).toHaveText('IntelliSense ready', { timeout: 60_000 })
  await page.evaluate(() => { const h = (window as any).picoHarness; h.editor.setPosition({ lineNumber: 4, column: 5 }); h.editor.focus(); h.editor.trigger('test', 'editor.action.triggerSuggest', {}) })
  await expect(page.locator('.suggest-widget')).toBeVisible()
  await page.keyboard.type('val')
  await expect(page.locator('.suggest-widget')).toContainText('value')
  const trace = await page.evaluate(() => (window as any).picoHarness.runtime.run('from machine import Pin, PWM\nprint("worker hello")\np=PWM(Pin(0))\np.freq(1000)\np.duty_u16(32768)', 1, () => {}))
  expect(trace.console).toContain('worker hello')
  expect(trace.events.length).toBeGreaterThan(100)
})

test('semantic diagnostics, signatures, navigation, rename, references and analysis restart', async ({ page }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/tests/pico-harness.html')
  await expect(page.locator('#status')).toHaveText('IntelliSense ready', { timeout: 60000 })
  const setSource = (source: string) => page.evaluate(source => { const h = (window as any).picoHarness; h.model.setValue(source); h.editor.focus() }, source)
  const markers = () => page.evaluate(() => { const h = (window as any).picoHarness; return h.monaco.editor.getModelMarkers({ resource: h.model.uri }).map((m: any) => ({ message: m.message, line: m.startLineNumber })) })
  await setSource('from machine import Pin, PWM\nimport time\npwm = PWM(Pin(0))\npwm.duty_u16("bad")\ntime.sleep_ms(1)\nmissing_name\n')
  await expect.poll(markers).toEqual(expect.arrayContaining([expect.objectContaining({ line: 4 }), expect.objectContaining({ line: 6 })]))
  expect((await markers()).some((m: any) => m.line === 5)).toBe(false)
  await setSource('from machine import Pin, PWM\nimport time\npwm = PWM(Pin(0))\npwm.duty_u16(12000)\ntime.sleep_ms(1)\n')
  await expect.poll(markers).toEqual([])
  await page.evaluate(() => { const h = (window as any).picoHarness; h.editor.setPosition({ lineNumber: 4, column: 14 }); h.editor.trigger('test', 'editor.action.triggerParameterHints', {}) })
  await expect(page.locator('.parameter-hints-widget')).toContainText('value')
  await expect(page.locator('.parameter-hints-widget')).toContainText('int')
  await page.keyboard.press('Escape')
  await setSource('def twice(value: int) -> int:\n    return value * 2\n\nresult = twice(21)\nprint(result)\n')
  await page.evaluate(() => { const h = (window as any).picoHarness; h.editor.setPosition({ lineNumber: 4, column: 11 }); h.editor.trigger('test', 'editor.action.revealDefinition', {}) })
  await expect.poll(() => page.evaluate(() => (window as any).picoHarness.editor.getPosition().lineNumber)).toBe(1)
  await page.evaluate(() => { const h = (window as any).picoHarness; h.editor.setPosition({ lineNumber: 4, column: 2 }); h.editor.trigger('test', 'editor.action.rename', {}) })
  const rename = page.locator('.rename-input')
  await expect(rename).toBeVisible()
  await rename.fill('answer')
  await page.keyboard.press('Enter')
  await expect.poll(() => page.evaluate(() => (window as any).picoHarness.model.getValue())).toContain('print(answer)')
  await page.evaluate(() => (window as any).picoHarness.editor.focus())
  await page.keyboard.press('Control+z')
  await expect.poll(() => page.evaluate(() => (window as any).picoHarness.model.getValue())).toContain('print(result)')
  await page.evaluate(() => { const h = (window as any).picoHarness; h.editor.setPosition({ lineNumber: 4, column: 11 }); h.editor.trigger('test', 'editor.action.referenceSearch.trigger', {}) })
  await expect(page.locator('.peekview-widget')).toContainText('twice')
  await page.keyboard.press('Escape')
  await page.evaluate(() => (window as any).picoHarness.restart())
  await expect(page.locator('#status')).toHaveText('IntelliSense ready')
  await setSource('this_is_undefined\n')
  await expect.poll(markers).toEqual(expect.arrayContaining([expect.objectContaining({ line: 1 })]))
  expect(errors).toEqual([])
})

test('semantic import completion, hover, outline and auto-import code action', async ({ page }) => {
  test.setTimeout(60000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/tests/pico-harness.html')
  await expect(page.locator('#status')).toHaveText('IntelliSense ready', { timeout: 45000 })
  const action = (source: string, line: number, column: number, command: string) => page.evaluate(({ source, line, column, command }) => { const h = (window as any).picoHarness; h.model.setValue(source); h.editor.setPosition({ lineNumber: line, column }); h.editor.focus(); if (command) h.editor.trigger('test', command, {}) }, { source, line, column, command })
  await action('from machine import PW', 1, 23, 'editor.action.triggerSuggest')
  await expect(page.locator('.suggest-widget')).toContainText('PWM')
  await page.keyboard.press('Escape')
  await action('number = 42\nprint(number)', 2, 8, 'editor.action.showHover')
  await expect(page.locator('.monaco-hover')).toContainText('Literal[42]')
  await page.keyboard.press('Escape')
  await action('from machine import Pin\npin = Pin(0)', 2, 8, 'editor.action.showHover')
  await expect(page.locator('.monaco-hover')).toContainText('Pin')
  await expect(page.locator('.monaco-hover')).toContainText('GPIO')
  await page.keyboard.press('Escape')
  await action('def oscillator():\n    return 1000\n\nfrequency = oscillator()', 1, 5, 'editor.action.quickOutline')
  await expect(page.locator('.quick-input-widget')).toContainText('oscillator')
  await page.keyboard.press('Escape')
  await action('led = Pin(0)\n', 1, 8, '')
  await expect.poll(() => page.evaluate(() => { const h = (window as any).picoHarness; return h.monaco.editor.getModelMarkers({ resource: h.model.uri }).map((m: any) => m.message).join('\n') })).toContain('not defined')
  await page.evaluate(() => (window as any).picoHarness.editor.trigger('test', 'editor.action.quickFix', {}))
  await expect(page.locator('.action-widget').first()).toBeVisible()
  await page.getByText(/from machine import Pin/).last().click()
  await expect.poll(() => page.evaluate(() => (window as any).picoHarness.model.getValue())).toContain('from machine import Pin')
  expect(errors).toEqual([])
})

test('Pico cold readiness, completion, cancellation and worker memory measurements', async ({ page, context, browser }, testInfo) => {
  test.setTimeout(60000)
  const started = Date.now()
  await page.goto('/tests/pico-harness.html')
  await expect(page.locator('#status')).toHaveText('IntelliSense ready', { timeout: 45000 })
  const readyMs = Date.now() - started
  const completionStarted = Date.now()
  await page.evaluate(() => { const h = (window as any).picoHarness; h.model.setValue('from machine import Pin\nled=Pin(25,Pin.OUT)\nled.val'); h.editor.setPosition({ lineNumber: 3, column: 8 }); h.editor.trigger('test', 'editor.action.triggerSuggest', {}) })
  await expect(page.locator('.suggest-widget')).toContainText('value')
  const completionMs = Date.now() - completionStarted
  const runtime = await page.evaluate(async () => { const h = (window as any).picoHarness; const trace = await h.runtime.run('from machine import Pin, PWM\np=PWM(Pin(0))\np.freq(1000)\np.duty_u16(32768)', 99, () => {}); let stopStarted = 0; const cancelled = h.runtime.run('while True: pass', 100, (phase: string) => { if (phase === 'running' && !stopStarted) { stopStarted = performance.now(); h.runtime.stop() } }).catch(() => 'cancelled'); await cancelled; return { elapsedMs: trace.elapsedMs, instructions: trace.instructions, events: trace.events.length, cancellationMs: performance.now() - stopStarted } })
  const main = await context.newCDPSession(page)
  const mainHeap = await main.send('Runtime.getHeapUsage')
  const cdp = await browser.newBrowserCDPSession()
  const { targetInfos } = await cdp.send('Target.getTargets')
  const workers = []
  for (const target of targetInfos.filter(t => t.type === 'worker')) {
    const { sessionId } = await cdp.send('Target.attachToTarget', { targetId: target.targetId, flatten: false })
    const heap = await new Promise<object>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Worker heap measurement timed out')), 5000)
      const receive = (message: any) => { if (message.sessionId !== sessionId) return; const value = JSON.parse(message.message); if (value.id !== 1) return; clearTimeout(timer); cdp.off('Target.receivedMessageFromTarget', receive); resolve(value.result) }
      cdp.on('Target.receivedMessageFromTarget', receive)
      void cdp.send('Target.sendMessageToTarget', { sessionId, message: JSON.stringify({ id: 1, method: 'Runtime.getHeapUsage' }) })
    })
    workers.push({ url: target.url.split('/').at(-1), heap })
    await cdp.send('Target.detachFromTarget', { sessionId })
  }
  const metrics = { environment: `${process.platform}/${process.arch}; Chromium ${browser.version()}; ${process.env.LABOR_PRODUCTION ? 'production' : 'development'}`, readyMs, completionMs, runtime, mainHeap, workers }
  console.log('PICO_METRICS', JSON.stringify(metrics))
  await testInfo.attach('pico-metrics.json', { body: JSON.stringify(metrics, null, 2), contentType: 'application/json' })
  await cdp.detach(); await main.detach()
})
