import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { examples } from '../../src/lib/circuit'

const tab = (page: Page, name: 'Circuit' | 'Results' | 'Pico Code') => page.getByRole('tablist', { name: 'Workspace' }).getByRole('tab', { name, exact: true })
const savedDocument = (page: Page) => page.evaluate(() => localStorage.getItem('labor-playground.document.v1'))

async function capturedLogs(page: Page) {
  const circuit = structuredClone(examples.find(example => example.id === 'pico-console')!.document)
  circuit.pico!.source = `import time
import scope
print("ordinary console output")
time.sleep_ms(10)
scope.log("target", 1.5, "V")
scope.log("counter", 1)
time.sleep_ms(20)
scope.log("target", 3, "V")
scope.log("counter", 2)
time.sleep_ms(60)
`
  circuit.automations = [
    { id: 'A1', name: 'Raise CV', enabled: true, trigger: { kind: 'time', atMs: 40 }, action: { target: 'cv', value: 3, durationMs: 0 } },
    { id: 'A2', name: 'After recording', enabled: true, trigger: { kind: 'time', atMs: 200 }, action: { target: 'cv', value: 1, durationMs: 0 } },
    { id: 'A3', name: 'Disabled event', enabled: false, trigger: { kind: 'time', atMs: 50 }, action: { target: 'cv', value: 2, durationMs: 0 } },
  ]
  await page.addInitScript(document => localStorage.setItem('labor-playground.document.v1', JSON.stringify(document)), circuit)
  await page.goto('/')
  await page.getByRole('button', { name: 'Simulate', exact: true }).click()
  await expect(page.getByLabel('Simulation status')).toHaveAttribute('data-state', 'ready', { timeout: 45_000 })
  await tab(page, 'Results').click()
  return page.getByRole('region', { name: 'Oscilloscope', exact: true })
}

test('Pico numeric logs use simulation time and work without analog probes', async ({ page }, testInfo) => {
  const scope = await capturedLogs(page)
  await expect(scope.getByRole('checkbox', { name: 'Show Pico logs', exact: true })).toBeChecked()
  await expect(scope.getByLabel('Pico log target waveform', { exact: true })).toBeVisible()
  await expect(scope.getByLabel('Pico log counter waveform', { exact: true })).toBeVisible()
  await expect(scope.getByText('No probe attached', { exact: true })).toHaveCount(2)
  await page.getByLabel('Recording time milliseconds').fill('0')
  await expect(scope.getByLabel('Pico log target value', { exact: true })).toHaveText('—')
  await page.getByLabel('Recording time milliseconds').fill('20')
  await expect(scope.getByLabel('Pico log target value', { exact: true })).toHaveText('1.500 V')
  await expect(scope.getByLabel('Pico log counter value', { exact: true })).toHaveText('1.000')
  await page.getByLabel('Recording time milliseconds').fill('50')
  await expect(scope.getByLabel('Pico log target value', { exact: true })).toHaveText('3.000 V')
  await expect(scope.getByLabel('Pico log counter value', { exact: true })).toHaveText('2.000')
  await page.getByLabel('Time per division', { exact: true }).selectOption('10')
  await scope.screenshot({ path: testInfo.outputPath('scope-extras-desktop.png'), style: '.project-toolbar { visibility: hidden; }' })
  await tab(page, 'Pico Code').click()
  await expect(page.getByLabel('Pico serial console')).toContainText('ordinary console output')
  await expect(page.getByLabel('Pico serial console')).not.toContainText('scope.log')
})

test('scope visibility switches are independent and event seeking shares the Pico time window', async ({ page }) => {
  const scope = await capturedLogs(page)
  const before = await savedDocument(page)
  const automationEvents = scope.getByLabel('Oscilloscope automation events', { exact: true })
  await expect(automationEvents.getByRole('button')).toHaveCount(1)
  await expect(automationEvents).not.toContainText('After recording')
  await expect(automationEvents).not.toContainText('Disabled event')
  await scope.getByRole('checkbox', { name: 'Show automation events', exact: true }).uncheck()
  await expect(automationEvents).toHaveCount(0)
  await expect(scope.getByTestId('scope-automation-marker')).toHaveCount(0)
  await expect(scope.locator('[data-log-event]')).toHaveCount(0)
  await expect(scope.getByLabel('Pico log target waveform', { exact: true })).toBeVisible()
  await scope.getByRole('checkbox', { name: 'Show Pico logs', exact: true }).uncheck()
  await expect(scope.getByLabel('Pico log target waveform', { exact: true })).toHaveCount(0)
  await scope.getByRole('checkbox', { name: 'Show automation events', exact: true }).check()
  await expect(automationEvents.getByRole('button', { name: 'Seek Raise CV at 40 ms', exact: true })).toBeVisible()
  await tab(page, 'Circuit').click()
  await tab(page, 'Results').click()
  await expect(scope.getByRole('checkbox', { name: 'Show Pico logs', exact: true })).not.toBeChecked()
  await expect(scope.getByRole('checkbox', { name: 'Show automation events', exact: true })).toBeChecked()
  await scope.getByRole('checkbox', { name: 'Show Pico logs', exact: true }).check()
  const targetToggle = scope.getByRole('button', { name: 'Toggle Pico log target', exact: true })
  await targetToggle.click()
  await expect(targetToggle).toHaveAttribute('aria-pressed', 'false')
  await expect(scope.getByLabel('Pico log target waveform', { exact: true })).toHaveCount(0)
  await expect(scope.getByLabel('Pico log counter waveform', { exact: true })).toBeVisible()
  await targetToggle.click()
  await page.getByLabel('Time per division', { exact: true }).selectOption('1')
  await automationEvents.getByRole('button', { name: 'Seek Raise CV at 40 ms', exact: true }).click()
  await expect(page.getByLabel('Recording time milliseconds')).toHaveValue('40')
  await expect(scope.getByLabel('Pico log target value', { exact: true })).toHaveText('3.000 V')
  await expect(scope.getByTestId('scope-automation-marker')).toHaveAttribute('data-time', '0.04')
  await expect(scope.locator('[data-log-event="A1"]')).toHaveCount(2)
  const physicalWaveform = scope.getByLabel('Voltage versus time for scope channels 1 and 2', { exact: true })
  const loggedWaveform = scope.getByLabel('Pico log target waveform', { exact: true })
  const start = await physicalWaveform.getAttribute('data-window-start')
  expect(Number(start)).toBeGreaterThan(0)
  await expect(loggedWaveform).toHaveAttribute('data-window-start', start!)
  await expect(loggedWaveform).toHaveAttribute('data-window-end', (await physicalWaveform.getAttribute('data-window-end'))!)
  const logCursor = scope.getByRole('slider', { name: 'Pico log target recording cursor', exact: true })
  await logCursor.focus()
  await logCursor.press('ArrowRight')
  expect(Number(await page.getByLabel('Recording time milliseconds').inputValue())).toBeGreaterThan(40)
  expect(await savedDocument(page)).toBe(before)
})

test('scope extras fit a phone and discard stale data after source changes', async ({ page }, testInfo) => {
  const scope = await capturedLogs(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel('Time per division', { exact: true }).selectOption('10')
  await scope.getByRole('button', { name: 'Seek Raise CV at 40 ms', exact: true }).click()
  await expect(scope.getByLabel('Pico log target value', { exact: true })).toHaveText('3.000 V')
  await expect(scope.getByTestId('scope-automation-marker')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await scope.screenshot({ path: testInfo.outputPath('scope-extras-mobile.png'), style: '.project-toolbar { visibility: hidden; }' })
  await tab(page, 'Pico Code').click()
  const editor = page.getByRole('textbox', { name: 'Pico main.py editor', exact: true })
  await editor.focus()
  await editor.press('Control+End')
  await page.keyboard.insertText('\n# next recording')
  await expect(page.getByText('Source or wiring changed — Run to capture', { exact: true })).toBeVisible()
  await tab(page, 'Results').click()
  await expect(page.getByLabel('Recording timeline')).toBeDisabled()
  await expect(scope.getByLabel('Pico log target waveform', { exact: true })).toHaveCount(0)
  await expect(scope.getByTestId('scope-automation-marker')).toHaveCount(0)
  await expect(scope.getByRole('button', { name: 'Seek Raise CV at 40 ms', exact: true })).toHaveCount(0)
  await expect(scope.getByRole('checkbox', { name: 'Show Pico logs', exact: true })).toBeChecked()
  await expect(scope.getByRole('checkbox', { name: 'Show automation events', exact: true })).toBeChecked()
})
