import { expect, test } from '@playwright/test'

const key = 'labor-playground.document.v1'
test('SPICE file review, pin mapping, placement, shared edits, undo and recovery', async ({ page, browser }) => {
  await page.goto('/')
  const library = page.getByRole('complementary', { name: 'Parts library', exact: true })
  await library.getByRole('button', { name: 'Clear board', exact: true }).click()
  const trigger = library.getByRole('button', { name: 'Import SPICE model', exact: true })
  await trigger.focus(); await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Import SPICE model', exact: true })
  const source = dialog.getByRole('textbox', { name: 'SPICE source', exact: true })
  await expect(source).toBeFocused()
  await source.fill('.include "unsupported.lib"')
  await expect(dialog.getByRole('button', { name: 'Import model', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('alert')).toContainText('Only D, NPN and PNP')
  await dialog.locator('input[type=file]').setInputFiles({ name: 'parts.lib', mimeType: 'text/plain', buffer: Buffer.from('* Test library\n.model TEST_D D(IS=1n N=1.5)\n.model TEST_Q NPN(IS=10f BF=150)') })
  await dialog.getByRole('combobox', { name: 'Model entry point' }).selectOption('TEST_Q')
  await expect(dialog).toContainText('1 = Collector, 2 = Base, 3 = Emitter')
  await dialog.getByRole('textbox', { name: 'Model description' }).fill('Test model; verify physical pinout.')
  await page.screenshot({ path: '/tmp/labor-spice-import.png' })
  await dialog.getByRole('button', { name: 'Import model', exact: true }).click()
  await page.getByRole('button', { name: /^A10, available$/ }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-part="Q1"]')).toHaveAttribute('aria-label', /TEST_Q/)
  await page.locator('[data-part="Q1"]').focus()
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  await expect(inspector.getByRole('combobox', { name: 'Component model' })).toHaveValue(/model_/)
  await inspector.getByRole('button', { name: 'Edit model', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit SPICE model', exact: true })
  await editor.getByRole('textbox', { name: 'SPICE source', exact: true }).fill('.model TEST_Q PNP(BF=200)')
  await expect(editor.getByRole('button', { name: 'Save model' })).toBeDisabled()
  await editor.getByRole('textbox', { name: 'SPICE source', exact: true }).fill('.model TEST_Q NPN(BF=200)')
  await editor.getByRole('button', { name: 'Save model' }).click()
  const saved = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)
  await expect.poll(async () => (await saved()).customComponents[0].spice.parameters.BF).toBe(200)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await saved()).customComponents[0].spice.parameters.BF).toBe(150)
  await page.reload()
  await expect(library.getByRole('button', { name: 'TEST_Q', exact: true })).toBeVisible()
  await trigger.click()
  await page.getByRole('dialog').getByRole('textbox', { name: 'SPICE source' }).fill('.model CANCELLED D')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect.poll(async () => (await saved()).customComponents.length).toBe(1)
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit', exact: true }).click()
  const filePath = await (await downloadEvent).path()
  const context = await browser.newContext()
  const fresh = await context.newPage(); await fresh.goto('/')
  await fresh.locator('input[type=file]').setInputFiles(filePath!)
  await expect(fresh.locator('[data-part="Q1"]')).toHaveAttribute('aria-label', /TEST_Q/)
  await context.close()
})

test('assign imported diode, measure it, and hide stale readings after an electrical model edit', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Load example' }).selectOption('voltage-divider')
  await expect.poll(() => page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null')?.title, key)).toBe('Voltage divider')
  const doc = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)
  doc.parts[0].value = 1000
  doc.parts[1] = { ...doc.parts[1], kind: 'diode', id: 'D1', value: 1 }
  await page.locator('input[type=file]').setInputFiles({ name: 'diode.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(doc)) })
  await page.getByRole('button', { name: 'Import SPICE model', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('textbox', { name: 'SPICE source', exact: true }).fill('.model TEST_D D(IS=1n N=1.5 RS=2 CJO=4p)')
  await expect(dialog).toContainText('1 = Anode, 2 = Cathode')
  await dialog.getByRole('button', { name: 'Import model', exact: true }).click()
  await page.locator('[data-part="D1"]').focus()
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  await inspector.getByRole('combobox', { name: 'Component model' }).selectOption({ label: 'TEST_D' })
  const status = page.getByRole('status', { name: 'Simulation status', exact: true })
  await expect(status).toHaveAttribute('data-state', 'ready', { timeout: 45_000 })
  await expect(inspector.getByLabel('DC current Anode → Cathode', { exact: true })).toContainText('mA')
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Auto update', exact: true }).uncheck()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await inspector.getByRole('button', { name: 'Edit model', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'Model name' }).fill('Renamed diode')
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await expect(status).toHaveAttribute('data-state', 'ready')
  await inspector.getByRole('button', { name: 'Edit model', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'SPICE source' }).fill('.model TEST_D D(IS=1n N=2 RS=2 CJO=4p)')
  await dialog.getByRole('button', { name: 'Save model' }).click()
  await expect(status).toHaveAttribute('data-state', 'stale')
  await expect(inspector.getByLabel('DC current Anode → Cathode', { exact: true })).toHaveCount(0)
})
