import { expect, test, type Page } from '@playwright/test'

const source = '.SUBCKT DIV IN OUT RET\nR1 IN OUT 1k\nR2 OUT RET 1k\n.ENDS DIV'
const key = 'labor-playground.document.v1'
const saved = (page: Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), key)
const terminal = (page: Page, id: string) => page.getByRole('button', { name: new RegExp(`^${id.toUpperCase()}, (available|occupied)$`) })
async function openImport(page: Page, text = source) {
  await page.getByRole('button', { name: 'Import SPICE model', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('textbox', { name: 'SPICE source', exact: true }).fill(text)
  return dialog
}

test('subcircuit pin review, placement, movement, schema and recovery preserve a remapped package', async ({ page, browser }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  const dialog = await openImport(page)
  await expect(dialog).toContainText('Virtual DIP-4 package')
  await dialog.getByRole('combobox', { name: 'Package pin for IN', exact: true }).selectOption('2')
  await expect(dialog.getByRole('button', { name: 'Import model', exact: true })).toBeDisabled()
  await dialog.getByRole('combobox', { name: 'Package pin for RET', exact: true }).selectOption('1')
  await dialog.getByRole('combobox', { name: 'Package pin for OUT', exact: true }).selectOption('0')
  await dialog.getByRole('button', { name: 'Import model', exact: true }).click()
  await terminal(page, 'e10').click(); await page.keyboard.press('Escape')
  const component = page.locator('[data-part="X1"]')
  await expect(component).toHaveAttribute('aria-label', /DIV/)
  await expect(component.locator('[data-pin]')).toHaveCount(4)
  await component.focus()
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  for (const [index, name] of ['OUT', 'RET', 'IN', 'NC'].entries()) await expect(inspector.locator('.pin-row').nth(index)).toContainText(name)
  await component.press('ArrowRight')
  await expect.poll(async () => (await saved(page))?.parts[0]?.pins).toEqual(['e11', 'e12', 'f12', 'f11'])
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await saved(page))?.parts[0]?.pins).toEqual(['e10', 'e11', 'f11', 'f10'])
  await page.getByRole('tab', { name: 'Schema', exact: true }).click()
  await expect(page.getByTestId('schematic-drawing')).toContainText('DIV')
  await expect(page.getByTestId('schematic-drawing').locator('[data-schema-pin]')).toHaveCount(4)
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await page.reload(); await expect(component).toHaveAttribute('aria-label', /DIV/)
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit', exact: true }).click()
  const path = await (await downloadEvent).path()
  const context = await browser.newContext(), fresh = await context.newPage()
  await fresh.goto('/'); await fresh.locator('input[type=file]').setInputFiles(path!)
  await expect(fresh.locator('[data-part="X1"]')).toHaveAttribute('aria-label', /DIV/)
  await expect.poll(async () => (await saved(fresh))?.customComponents[0]?.pinMap).toEqual([2, 0, 1])
  await context.close()
  expect(errors).toEqual([])
})

test('subcircuit electrical edits stale measured results and undo restores the shared definition', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  const dialog = await openImport(page)
  await dialog.getByRole('button', { name: 'Import model', exact: true }).click()
  await terminal(page, 'e10').click(); await page.keyboard.press('Escape')
  await expect.poll(async () => (await saved(page))?.parts.length).toBe(1)
  const doc = await saved(page)
  doc.wires = [{ id: 'W1', from: 'cv', to: 'd10', color: '#ffffff' }, { id: 'W2', from: 'gnd', to: 'g11', color: '#ffffff' }]
  doc.probes = { CH1: 'e10', CH2: 'e11' }
  await page.locator('input[type=file]').setInputFiles({ name: 'subcircuit.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(doc)) })
  const status = page.getByRole('status', { name: 'Simulation status', exact: true })
  await expect(status).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.locator('[data-part="X1"]').focus()
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  await expect(inspector.getByLabel('DC current Into pin 1 (IN)', { exact: true })).toHaveText('2.500 mA')
  await expect(inspector).not.toContainText('Current and power are unavailable')
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Auto update', exact: true }).uncheck()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await inspector.getByRole('button', { name: 'Edit model', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'SPICE source', exact: true }).fill(source.replace('OUT RET 1k', 'OUT RET 2k'))
  await dialog.getByRole('button', { name: 'Save model', exact: true }).click()
  await expect(status).toHaveAttribute('data-state', 'stale')
  await expect(inspector.getByLabel('DC current Into pin 1 (IN)', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await saved(page))?.customComponents[0]?.spice.elements[1].value).toBe(1000)
})

test('two-pin imports rotate as leaded parts and reference-ground imports explain their extra pin', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  const dialog = await openImport(page, '.SUBCKT CAP P N\nR1 P inner 0.1\nC1 inner N 10u\nR2 inner N 100Meg\n.ENDS')
  await expect(dialog).toContainText('Two-lead component')
  await dialog.getByRole('button', { name: 'Import model', exact: true }).click()
  await page.getByRole('button', { name: 'Rotate placement', exact: true }).click()
  await terminal(page, 'a10').click(); await page.keyboard.press('Escape')
  await expect.poll(async () => (await saved(page))?.parts[0]?.pins).toEqual(['a10', 'd10'])
  await openImport(page, '.SUBCKT AMP IN OUT\nR1 IN 0 1Meg\nE1 OUT 0 IN 0 2\n.ENDS')
  await expect(dialog.getByRole('combobox', { name: 'Package pin for 0 (reference)', exact: true })).toBeVisible()
  await expect(dialog).toContainText('reference pin must be wired to workbench GND')
  await page.screenshot({ path: '/tmp/labor-subcircuit-import.png' })
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect.poll(async () => (await saved(page))?.customComponents.length).toBe(1)
})
