import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'

test('the utility example captures, runs its saved suite, exports and recovers', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Load example').selectOption('cascadable-utility-cell')
  const status = page.getByRole('status', { name: 'Simulation status', exact: true })
  await expect(status).toHaveAttribute('data-state', 'ready', { timeout: 60_000 })
  await expect(page.locator('.diagnostic, .error-copy')).toHaveCount(0)
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!))
  expect(saved.parts).toHaveLength(112)
  await expect(page.getByText('112 / 128 parts placed', { exact: true })).toBeVisible()
  expect(saved.automationProgram.tests).toHaveLength(8)
  await page.getByRole('region', { name: 'Breadboard view', exact: true }).screenshot({ path: testInfo.outputPath('utility-board.png') })
  await page.locator('[data-part="A_SW1"]').focus()
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  await inspector.getByRole('checkbox', { name: 'Throw 0', exact: true }).check()
  await expect(inspector.getByRole('checkbox', { name: 'Throw 1', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(inspector.getByRole('checkbox', { name: 'Throw 0', exact: true })).not.toBeChecked()
  await page.getByRole('tab', { name: 'Automations', exact: true }).click()
  await page.getByRole('button', { name: 'Tests (8)', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Circuit tests', exact: true })
  await panel.getByRole('button', { name: 'Run all tests', exact: true }).click()
  await expect(panel.locator('.test-verdict.passed')).toHaveCount(8, { timeout: 90_000 })
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('labor-playground.document.v1')!))).toEqual(saved)
  await panel.screenshot({ path: testInfo.outputPath('utility-tests.png') })
  await page.getByRole('tab', { name: 'Schema', exact: true }).click()
  await expect(page.locator('.schematic-sheet')).toContainText('SSI2162')
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await expect(status).toHaveAttribute('data-state', 'ready', { timeout: 60_000 })
  await page.getByRole('button', { name: 'Fit entire capture', exact: true }).click()
  await expect(page.locator('.scope-event-description small').filter({ hasText: 'A_SW1 → throw 1' })).toBeVisible()
  await expect(inspector.getByLabel('DC current A common → 0', { exact: true })).toBeVisible()
  await page.getByLabel('Recording time milliseconds', { exact: true }).fill('50')
  await expect(inspector.getByLabel('Recorded component state', { exact: true })).toHaveText('Throw 1')
  await expect(inspector.getByRole('checkbox', { name: 'Throw 0', exact: true })).not.toBeChecked()
  await page.getByLabel('Recording time milliseconds', { exact: true }).fill('65')
  await expect(inspector.getByLabel('Recorded component state', { exact: true })).toHaveText('Throw 0')
  await page.getByRole('button', { name: 'Recording start', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('utility-results.png'), fullPage: true })
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export circuit', exact: true }).click()
  const path = await (await download).path()
  expect(JSON.parse(await readFile(path!, 'utf8'))).toEqual(saved)
  await page.reload()
  await expect(page.getByLabel('Load example')).toHaveValue('cascadable-utility-cell')
  await expect(status).toHaveAttribute('data-state', 'ready', { timeout: 60_000 })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  expect(errors).toEqual([])
})

test('new adapters and switches expose their pins, reference selection and automation controls', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  const tray = page.getByRole('complementary', { name: 'Parts library', exact: true })
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  const search = tray.getByLabel('Find a component')
  for (const [query, name, id, hole, pins] of [
    ['OPA4197', 'OPA4197-style quad op-amp', 'U1', 'E1', 14],
    ['SSI2162', 'SSI2162-style dual VCA', 'U2', 'E10', 10],
    ['OPA197', 'OPA197-style op-amp', 'U3', 'E17', 8],
    ['DPDT', 'DPDT changeover switch', 'S1', 'E23', 6],
    ['SPDT changeover', 'SPDT changeover switch', 'S2', 'A28', 3],
  ] as const) {
    await search.fill(query)
    await tray.getByRole('button', { name, exact: true }).click()
    await page.getByRole('button', { name: `${hole}, available`, exact: true }).click()
    await expect(inspector.getByRole('heading', { name, exact: true })).toBeVisible()
    await expect(inspector.locator('.pin-row')).toHaveCount(pins)
    await expect(page.locator(`[data-part="${id}"] [data-pin]`)).toHaveCount(pins)
  }
  await inspector.getByRole('checkbox', { name: 'Throw 0', exact: true }).check()
  await page.getByRole('tab', { name: 'Automations', exact: true }).click()
  await page.getByRole('button', { name: 'Add automation', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox', { name: 'Control', exact: true }).selectOption('switch:S2')
  await dialog.getByRole('button', { name: 'Save automation', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('tab', { name: 'Circuit', exact: true }).click()
  await page.getByLabel('Load example').selectOption('precision-cv-reference')
  await page.locator('[data-part="U1"]').focus()
  await inspector.getByLabel('Reference voltage').selectOption('5')
  await expect(page.getByRole('status', { name: 'Simulation status', exact: true })).toHaveAttribute('data-state', 'ready')
  await page.getByRole('tab', { name: 'Results', exact: true }).click()
  await page.locator('.operating-point-panel > summary').click()
  await expect(page.getByLabel('CH2 DC voltage', { exact: true })).toContainText('5.00')
})
