import { useEffect, useRef, useState } from 'react'
import { Search, X, BookOpen, Keyboard } from 'lucide-react'

const topics = [
  { title: 'Read and export a schema', category: 'Measure', text: 'Schema shows the circuit as electrical symbols, including breadboard connections, values, pin numbers, supplies, and probes. Matching net labels connect across the sheet. Drag or scroll to pan, use the zoom buttons or Ctrl/Cmd + wheel to zoom, and Fit to frame the sheet. Click a component to inspect it. Enable Voltages to show recorded node voltages relative to GND at the same playback position as Results; play or scrub from either tab. Simulate again after electrical edits to refresh readings. SVG and PNG export the full annotated sheet with any enabled voltage readings. SCH downloads an editable KiCad legacy schematic and its symbols in a ZIP. Extract all files together, then open the .sch file in KiCad. Group outlines and enabled voltage snapshots are included as annotations. Under Component groups, select parts and apply a group name to place them together; Schema group in the inspector also assigns or clears membership. Groups support undo and save with the circuit.' },
  { title: 'Create custom components', category: 'Build', text: 'Choose Create custom component in the parts library. Define resistance in Ω versus current magnitude in A, or differential capacitance in F versus signed voltage in V. Engineering-unit selectors change table units. Curves use linear interpolation and constant endpoint extension; capture warnings report excursions. Save selects the definition for placement. In the inspector, assign compatible models, edit all shared instances, make an independent copy, or return to a linear built-in at the nominal value. Capacitor energy integrates V×C(V); every capture begins at its DC operating point. Cancel discards drafts; Save is one undoable edit. Up to 32 definitions with 2–64 points travel with project exports, recovery and folder sync. Clear board preserves definitions. Reassign or remove all instances before deleting a definition. Names are limited to 80 characters. Current axis: 0–1 A (minimum spacing 1 µA), resistance: 10 Ω–10 MΩ, slope at most 10⁹ Ω/A with positive differential resistance. Voltage axis: −100–100 V (minimum spacing 1 mV), capacitance: 100 pF–10 mF, slope at most 1 F/V. The editor shows these limits and validation errors.' },
  { title: 'Start your first experiment', category: 'Get started', text: 'Choose an example in the top bar. Open Overview for its instructions, parts list, and circuit checks. Start with the filter: select C1 and change its capacitance in the inspector. Simulate, then compare the input on CH1 with the output on CH2 in Results.' },
  { title: 'Place, move, and connect', category: 'Build', text: 'Choose a part from the library, then click a free breadboard hole. R rotates the placement; DIP chips turn 180° across the trench. Drag existing parts to move them. For a two-lead part, use Move beside a lead in the inspector to adjust spacing. W selects the wire tool: click the starting terminal, then the destination. Escape cancels placement or wiring. Select a part or wire and press Delete to remove it.' },
  { title: 'Understand the breadboard', category: 'Build', text: 'The five holes in each vertical strip connect internally. The center trench and split power rails remain separate. Patch supplies and ground to the rails with jumpers. Op-amps need visible supply connections. Toggle connections with C to inspect the internal connections. Choose H to pan, or hold Space while dragging over the board. F fits the whole workbench.' },
  { title: 'Simulate and troubleshoot', category: 'Measure', text: 'Simulate starts a fresh capture from the initial state. Cmd/Ctrl + Enter also works in the Pico editor. Analog circuits can auto update; Pico captures run manually. Choose a duration from 100 ms to 10 seconds in Results or Automations. If simulation is blocked, open Overview and fix the reported connections. Check power, ground, probe placement, and unconnected pins. Reset restarts the simulation engine.' },
  { title: 'Read the scope and recording', category: 'Measure', text: 'Choose CH1 or CH2, then click a terminal to attach a probe. Results contains the full oscilloscope and recording. Measurements provides cursors and waveform statistics; Trigger frames a crossing. Scrub or loop the recording to inspect component readings and LEDs at a selected time. Slow playback to inspect fast changes. DC operating point shows the initial state. Click a channel label to highlight its connection; drag the grip beneath the trace to resize the scope.' },
  { title: 'Pico and main.py', category: 'Code', text: 'Add a Pico from the parts library, then edit main.py in Code. Wire GPIO and Pico ground to your circuit. Simulate runs the selected capture duration; GPIO output drives the circuit and the serial console shows printed output. Project export and directory sync include the Python source inside circuit.json. Editor typing, selection, and undo remain local to the editor.' },
  { title: 'Automations, envelopes, and audio', category: 'Explore', text: 'In Automations, schedule knob ramps, switch changes, or gate presses at a time or voltage crossing. Each enabled action runs once per capture. Click a fired event to inspect its time; playback values appear beside automated controls. The EG terminal supplies a held gate, short trigger, or decay envelope. Fire starts a fresh capture. Audio / Power can loop verified settled periodic signals; edits stop audio playback.' },
  { title: 'Save, import, and recover', category: 'Files', text: 'The browser keeps a recovery copy when local storage is available. Export creates a portable JSON project with circuit, instruments, Pico source, automations, and custom component definitions. Import restores it. Loading an example, importing, clearing, and loading from a folder can be undone. Browser recovery is not a backup: export or sync a separate copy.' },
  { title: 'Sync a local folder', category: 'Files', text: 'Connect folder grants access through the browser’s File System Access API. Use a dedicated project folder. Sync now (Cmd/Ctrl + S) reads or writes circuit.json, including Pico source and automations. Changes made only in the folder load into the workbench; workbench changes save to the folder. If both changed, choose Keep workbench or Load folder version. Connecting an existing different project also asks which version to keep. Sync is manual, not a background watcher. Other files are left alone. Reconnect after reloading; Disconnect leaves files on disk. Folder access requires a supported browser such as desktop Chrome or Edge on HTTPS or localhost. Import and Export work when folder access is unavailable.' },
  { title: 'Model limits', category: 'Reference', text: 'Pico Labor is a virtual educational workbench inspired by LABOR, not an exact hardware replica. Instrument sources and component models are simplified. Recording playback replays the capture; the audio monitor loops settled cycles. Calibrated hardware models and live audio simulation are not provided.' },
]
const shortcuts = [
  ['Cmd/Ctrl + Enter', 'Simulate (also in Code)'], ['Cmd/Ctrl + S', 'Sync connected folder, or export'], ['Cmd/Ctrl + O', 'Import circuit'],
  ['Cmd/Ctrl + Z', 'Undo'], ['Cmd/Ctrl + Shift + Z / Ctrl + Y', 'Redo'], ['?', 'Open this guide'],
  ['V / W / H', 'Select / wire / pan'], ['R', 'Rotate part placement'], ['1 / 2', 'Place CH1 / CH2 probe'],
  ['Delete / Backspace', 'Delete selected part or wire'], ['Escape', 'Cancel tool or close dialog'], ['+ / −', 'Zoom in / out'], ['0', 'Fit breadboard'], ['F', 'Fit whole workbench'], ['C', 'Toggle connections'], ['[ / ]', 'Toggle parts library / inspector'],
  ['Alt + 1 / 2 / 3 / 4 / 5', 'Circuit / Code / Automations / Results / Overview'],
  ['Alt + 6', 'Schema'],
]
export function HelpDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null)
  const [query, setQuery] = useState('')
  const [section, setSection] = useState('All topics')
  useEffect(() => { if (open) dialog.current?.showModal(); else dialog.current?.close() }, [open])
  const search = query.trim().toLowerCase()
  const filtered = topics.filter(topic => (section === 'All topics' || section === topic.category) && `${topic.title} ${topic.text} ${topic.category}`.toLowerCase().includes(search))
  const keys = shortcuts.filter(row => row.join(' ').toLowerCase().includes(search))
  return <dialog ref={dialog} className="guide-dialog help-center" aria-labelledby="guide-title" onClose={onClose}>
    <header className="help-heading"><div><span className="help-eyebrow">PICO LABOR / FIELD GUIDE</span><h2 id="guide-title">Your workbench, explained.</h2><p>Build a circuit. Follow the signal. Find your next step.</p></div><button className="icon-button" aria-label="Close guide" onClick={onClose}><X size={20} /></button></header>
    <label className="help-search"><Search size={18} /><input autoFocus type="search" aria-label="Search guide" placeholder="Search wiring, Pico, saving, shortcuts…" value={query} onChange={event => setQuery(event.target.value)} /></label>
    <div className="help-layout"><nav aria-label="Guide topics">{['All topics', ...new Set(topics.map(topic => topic.category)), 'Shortcuts'].map(item => <button key={item} aria-pressed={section === item} onClick={() => setSection(item)}>{item === 'Shortcuts' ? <Keyboard size={15} /> : <BookOpen size={15} />}{item}</button>)}</nav>
    <div className="help-content">{section !== 'Shortcuts' && filtered.map(topic => <article key={topic.title}><span className="help-eyebrow">{topic.category}</span><h3>{topic.title}</h3><p>{topic.text}</p></article>)}
    {(section === 'All topics' || section === 'Shortcuts') && keys.length > 0 && <article><span className="help-eyebrow">QUICK REFERENCE</span><h3>Keyboard shortcuts</h3><p>Board shortcuts work in Circuit outside text fields. Project save and simulate also work in Code. Dialogs keep their own keyboard controls.</p><dl className="shortcut-list">{keys.map(([key, description]) => <div key={key}><dt><kbd>{key}</kbd></dt><dd>{description}</dd></div>)}</dl></article>}
    {((section === 'Shortcuts' ? keys.length === 0 : filtered.length === 0 && !(section === 'All topics' && keys.length))) && <p className="help-empty">No matching topics. Try “probe”, “folder”, or “simulate”.</p>}</div></div>
    <footer className="help-footer"><span>Everything runs locally in your browser.</span><button className="subtle-button" onClick={onClose}>Back to workbench</button></footer>
  </dialog>
}
